### ISSUE TITLE
Design a logo for Open Life Science

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#1]
as part of the open life science program, we'll want a logo of some sort for our projects. What should it look like? 

- would be nice to reflect aspects of openness as well as life science
- something that would work well as a sticker and as an icon, so not too complex

All ideas welcome - I'm also tagging this with the Hacktoberfest label so newcomers are welcome to suggest ideas (and we'll send you some copies of the sticker if we use your design, of course!)

**Comment by htmluke** [comment]
Hello! How could I participate? I can totally help you :)

**Comment by bebatut** [comment]
Hi @htmluke! We are happy that you want to participate 😄 
Let us know how we can help you

**Comment by shbr** [comment]
Hi... i'll work in a logo propose. ASAP i have an idea i'll send to you

**Comment by yochannah** [comment]
Wow, two volunteers already - thanks @htmluke @shbr! Feel free to share ideas as quick sketches or verbal descriptions first of all if it's easier ✨

**Comment by joelibaceta** [comment]
👍  nice I would like to share a logo propose too :) I'll work on that

**Comment by yochannah** [comment]
@joelibaceta wow, awesome - thanks! :)

**Comment by htmluke** [comment]
Nice! @bebatut do you have any document about your project? Something that describes the idea behind the project or explains what's the concept? Thanks for the oportunity <3

**Comment by bebatut** [comment]
We have a website (https://openlifesci.org/) in which we describe the project.
Let us know if you have questions or if something is not clear. Thanks a lot!

**Comment by bebatut** [comment]
We have now a logo (thanks to @htmluke)
