### ISSUE TITLE
Update landing page

### ISSUE THREAD

**Issue by SamGuay** [open-life-science/open-life-science.github.io#106]
I think it could be great to update the landing page because it can be misleading for people unaware of the program. (Just happened with my PI :sweat_smile:)

Here's some stuff that could be change to reflect the state of the program as of now: 
* Change the Application section (from open to closed)
* Maybe change the verb tenses from future to present? 

Another simple fix would be to redirect the landing page to https://openlifesci.org/ols-1?

**Comment by bebatut** [comment]
Thanks @SamGuay for pointing it. I was planning to do it but time ran... :smile:
