### ISSUE TITLE
Collecting example of potential projects

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/open-life-science.github.io#12]
[ ] Collect some of the Mozilla OL projects
[ ] Ask the experts and potential members

**Comment by bebatut** [comment]
Maybe find some life science projects (not only bioinformatics oriented)

**Comment by yochannah** [comment]
this coud be 
- creating an open source bioinformatics tool
- running a life science journal club....

**Comment by bebatut** [comment]
Check the previous demo calls and extract the ones related to life science
