### ISSUE TITLE
Formatting issue in participant descriptions

### ISSUE THREAD

**Issue by da5nsy** [open-life-science/open-life-science.github.io#143]
Currently the formatting of the [OLS1 participants section](https://openlifesci.org/ols-1/projects-participants/#participants) seems to be broken (code appearing where it presumably should not. 
Screenshot below.

Windows 10 - Firefox/Chrome/Edge

![Screenshot 2020-05-20 18 35 55](https://user-images.githubusercontent.com/3739866/82504195-c657c900-9ac8-11ea-8d60-e42057d17fce.png)

**Comment by bebatut** [comment]
Thanks a lot @da5nsy for reporting this issue.
They are some debugging leftover. It should be fixed with #145
