### ISSUE TITLE
Collect topics that we can add in the program

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/open-life-science.github.io#16]
Here are a few proposals for community aspects, please indicate if you would like to include them and leave a comment below if there are any modifications required in the content

Current tracks:

- **Track: Technical-development**
- **Track: Culture-community**

@yochannah has opened a PR with proposed contents #23

**Comment by malvikasharan** [comment]
Track: Culture-community

1. Developing community strategy: Canvas (inspired by previous MOL)
- Possible contents: mission statement, objectives and goals - roadmap, resources available (communication, skills), setting governance - leaders, possible teams with their scopes, main contact people, list of tasks for community members with their outcome, simple workflow/checklist for your teams/community (steps we need to take to reach the outcome)

Indicate if you have reviewed the topics:
[ ] @bebatut 
[ ] @malvikasharan 
[ ] @yochannah

**Comment by malvikasharan** [comment]
2. Creating a safe space 
- Content: [Ally skill](https://frameshiftconsulting.com/ally-skills-workshop/), establishing an effective [code of conduct](https://frameshiftconsulting.com/code-of-conduct-book/), onboarding new members, contribution guidelines, attracting a diverse audience, disemminating responsibilities, mental health and burnout 

Indicate if you have reviewed the topics:
[ ] @bebatut 
[ ] @malvikasharan 
[ ] @yochannah

**Comment by malvikasharan** [comment]
3. organising/attending Community engagement events
- Content: identifying engagement strategies, designing online/in-person meetings (from a selection of format to choose from), training events,  designing posters, writing abstract (suggested by @yochannah), designing your talk, preparing to run conference sessions or the entire conference

Indicate if you have reviewed the topics:
[ ] @bebatut 
[ ] @malvikasharan 
[ ] @yochannah

**Comment by malvikasharan** [comment]
4. Community assessment
- Content: tracking the success of teams/projects, designing survey, assessing the needs of your contributors, handling feedback, maintaining transparency, using social media for community outreach, exchanging notes with other leaders, documenting and sharing your periodic reports (mix it with data visualisation), identify effective tools for these tasks, reviewing current workflow based on feedback

Indicate if you have reviewed the topics:
[ ] @bebatut 
[ ] @malvikasharan 
[ ] @yochannah

**Comment by yochannah** [comment]
If we like and agree on these, I would be happy to start building call agendas for each of the calls.

**Comment by malvikasharan** [comment]
Thank you so much Yo. Thanks for putting these in the agenda. <3

**Comment by bebatut** [comment]
Looks good. I am just a bit afraid for the 3rd point that it will be already a lot on the week 6.

Do you want to add them in the agenda for the schedule in the syllabus? We could also already start a Gdoc per cohort call to aggregate the content there.

**Comment by malvikasharan** [comment]
I agree. We might be able to prioritize what to focus on and what can be offered as resources for later.

**Comment by malvikasharan** [comment]
Syllabus has been updated and finalised: https://openlifesci.org/syllabus
