### ISSUE TITLE
Ask for mentor / expert to check their information

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#164]
Hi,

All information about mentors and experts are listed in the [`_data/people.yaml`](https://github.com/open-life-science/open-life-science.github.io/blob/master/_data/people.yaml). Some are missing for some people and we would love to have them to help us to assign mentors to projects and later to help mentors and mentees to find experts.

Mentors, experts,
We would love you to check your information (list of possible information below). You are listed by your GitHub username (using alphabetical order). 

If anything is missing, you could:
- submit a Pull Request with the changes on  [`_data/people.yaml`](https://github.com/open-life-science/open-life-science.github.io/blob/master/_data/people.yaml),
- comment on this issue with the changes, or
- send us the changes by email at team@openlifesci.org

Thanks a lot

--- 
Possible information:

- **first-name (required)**
- **last-name (required)**
- twitter
- email
- website
- gitter
- orcid
- affiliation 
- **country (required)**
- **pronouns (required)**
- **expertise (What topics can you help others out with? list of keywords, required)**
- **life-science-expertise (What area of life science are you working on?, required)**
- **description (A sentence or three about you!, required)**

**Comment by lauracion** [comment]
Nice! Thank you! My GH user is not listed yet, so I am wondering if I should add myself here or not 😃 Thank you!

**Comment by yochannah** [comment]
@lauracion please do, and let us know if you need any help! 💚

**Comment by sgibson91** [comment]
Reviewed my entry and it looks great, thanks! 👾

**Comment by klauer2207** [comment]
Thank you, all fine on my profile!

**Comment by burkemlou** [comment]
Hi, there a couple of things needed on my profile.

Country: Australia
Expertise: add 'e-learning' 
Life-science expertise: add 'parasitology', 'microbiology', 'host-pathogen interactions'
Bio: My name is misspelled, it should be Melissa.

Thanks!

**Comment by yvanlebras** [comment]
Perfect on my side

**Comment by ArielleBL** [comment]
Hi there, the two required bits missing from my profile are: 

    **affiliation: University of Cambridge
    country: UK**
   
Otherwise all looks great thanks!
