### ISSUE TITLE
Fix the profile boxes to contain text

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/open-life-science.github.io#169]
# Profile boxes online appear a bit glitchy

Some text from the text box seem to skip (not contained)

![image](https://user-images.githubusercontent.com/5370471/86368072-aba27380-bc74-11ea-98a1-4f762a612c88.png)

**Comment by bebatut** [comment]
I can not reproduce that issue. @malvikasharan is it still the case for you?

**Comment by Lovelyfin00** [comment]
Hi @bebatut
Is this issue still open?
If yes, I would love to contribute to it
I'm an outreachy applicant

**Comment by bebatut** [comment]
Thanks @Lovelyfin00 for the interest. I did not manage to see this issue. Maybe you could investigate if it is still the case on the website https://openlifesci.org/people

**Comment by Lovelyfin00** [comment]
I could not find the issue too. The page is fully responsive on all devices and I checked

**Comment by bebatut** [comment]
I close this issue then. Thanks @Lovelyfin00 for checking it
