### ISSUE TITLE
Github badge

### ISSUE THREAD

**Issue by Sulstice** [open-life-science/open-life-science.github.io#172]
Would be sick to have a badge associated with open life science!

**Comment by Sulstice** [comment]
[![OSL](https://img.shields.io/badge/Supported%20By-Open%20Life%20Science-20b85f.svg)]()

as a start?

**Comment by yochannah** [comment]
Looove it @Sulstice! Made a few tweaks to include some alt text for screen readers and fixed it to link to the OLS homepage - also added a few more for specific cohorts and roles. What do you think? Also, where should we put this - the OLS homepage readme? 

```markdown
[![OLS-1 - part of Open Life Science](https://img.shields.io/badge/OLS--1-Open%20Life%20Science-20b85f.svg)](https://openlifesci.org/ols-1)
[![OLS-2 - part of Open Life Science](https://img.shields.io/badge/OLS--2-Open%20Life%20Science-20b85f.svg)](https://openlifesci.org/ols-2)
[![Project lead - part of Open Life Science](https://img.shields.io/badge/Project%20Lead-Open%20Life%20Science-20b85f.svg)](https://openlifesci.org/)
[![Mentor - part of Open Life Science](https://img.shields.io/badge/Mentor-Open%20Life%20Science-20b85f.svg)](https://openlifesci.org/)
[![Expert - part of Open Life Science](https://img.shields.io/badge/Expert-Open%20Life%20Science-20b85f.svg)](https://openlifesci.org/)
```
[![OLS-1 - part of Open Life Science](https://img.shields.io/badge/OLS--1-Open%20Life%20Science-20b85f.svg)](https://openlifesci.org/ols-1)
[![OLS-2 - part of Open Life Science](https://img.shields.io/badge/OLS--2-Open%20Life%20Science-20b85f.svg)](https://openlifesci.org/ols-2)
[![Project lead - part of Open Life Science](https://img.shields.io/badge/Project%20Lead-Open%20Life%20Science-20b85f.svg)](https://openlifesci.org/)
[![Mentor - part of Open Life Science](https://img.shields.io/badge/Mentor-Open%20Life%20Science-20b85f.svg)](https://openlifesci.org/)
[![Expert - part of Open Life Science](https://img.shields.io/badge/Expert-Open%20Life%20Science-20b85f.svg)](https://openlifesci.org/)

**Comment by Sulstice** [comment]
Ya! These look awesome! I also have something I can try tonight. I took your svg from your website and I believe I can host the badge online with your logo. Maybe deploy to a free service like vercel or heroku

**Comment by yochannah** [comment]
I think we can probably just use https://shields.io/ - no need for any extra service unless I'm missing something? (this is entirely possible 😆 )

**Comment by Sulstice** [comment]
Hey @yochannah Sorry for the delay in response~ (currently moving states so its a little hairy of when I get computer time). I wanted to get your logo embedded into the badge.

I did try with the img shields and others but my main issue was actually the svg hosting of your logo that wasn't blocked. If you use github/gists I get a lot of content blocks :(. So I was thinking we can deploy a simple flask app with the shield and logo of your org and throw it in.

Check out the gist:

https://gist.github.com/Sulstice/c3271e3667ffc4b27845dd6f7687645a

I'm still working on the coloring of your logo - perhaps a lighter shade of green.

**Comment by yochannah** [comment]
Ahhhhh, that makes sense! The logo is really supposed to go on a white background - I wonder if there's a way to make the background lighter on the left?

**Comment by yochannah** [comment]
Closing this issue as stale.
