### ISSUE TITLE
[css fix needed] Bug: people avatars not visible on community page for small screen

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#179]
In the page https://openlifesci.org/community, the people avatars are not visible on small screen

![Screenshot_20200727-200132_Firefox](https://user-images.githubusercontent.com/1842467/88575399-195b7880-d044-11ea-8c45-2509da6fa7db.png)

It should like:

![Screenshot 2020-09-28 at 17 41 07](https://user-images.githubusercontent.com/1842467/94454503-36323a80-01b2-11eb-96c5-1733ece5dbcf.png)

**Comment by DDuplinszki** [comment]
Hi there! Can I work on this issue?

**Comment by yochannah** [comment]
@DDuplinszki amazing - yes, please do! 🙌  let us know if you have any questions.

**Comment by bebatut** [comment]
@DDuplinszki fixes it with #214
