### ISSUE TITLE
Update schedule

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/open-life-science.github.io#197]
# Summary

- [ ] week-5: Skill-up: GitHub tutorial
- [ ] week-9: Skill-up: Ally skills and self-care workshop: Make it an open call for mentors and mentees
- [ ] Week 12: Update career sessions a panel only
- [ ] Week-13: Skill-up: creative writing and storytelling for final presentation

**Comment by malvikasharan** [comment]
I can find some time in the weekend to create this PR. But if someone's up to update it earlier, please go ahead.

**Comment by bebatut** [comment]
Done by @malvikasharan in #212
