### ISSUE TITLE
add project participant status 

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#198]
add a status field for each participant, with three statuses available to all ols-2 participants: active, inactive, or graduated

**Comment by Lovelyfin00** [comment]
Hello @bebatut
I'm an outreachy applicant and would love to contribute to this
Can more explanation be given on the issue?
Thank you

**Comment by Ososeomo** [comment]
Is this issue still available to be worked on @bebatut ? if yes, ill like to work on it

**Comment by Lovelyfin00** [comment]
Yes

**Comment by vasconsaurus** [comment]
working on it, but if there is anyone else working on it please let me know 🙈

**Comment by vasconsaurus** [comment]
**Update**
- updated the `projects-participants.md` to show the status
- tested with one project by updating the `ols-x-status.yaml`
- currently waiting for the data to update the status of the projects

<img width="389" alt="Screen Shot 2022-10-21 at 09 39 46" src="https://user-images.githubusercontent.com/87862340/197197858-4cbb7608-25d9-402e-9293-b29d1284e7aa.png">
<img width="678" alt="Screen Shot 2022-10-21 at 09 40 01" src="https://user-images.githubusercontent.com/87862340/197197876-baf06199-798f-4122-93fc-2fc68e78708e.png">
<img width="551" alt="Screen Shot 2022-10-21 at 09 40 13" src="https://user-images.githubusercontent.com/87862340/197197896-619fc47a-e124-4cef-98d7-a984c7a497bb.png">
