### ISSUE TITLE
Add google translate button to homepage

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#199]
This should probably go in the footer of the site so it'a accessible for anyone (or some other prominent but standard place) - see https://www.dummies.com/education/internet-basics/how-to-install-google-translates-website-translator-plugin/ for more info.

**Comment by devil-cyber** [comment]
I would like to work on this. It would be great if you could assign this to me

**Comment by yochannah** [comment]
@devil-cyber fabulous, go ahead! 😍

**Comment by devil-cyber** [comment]
@yochannah I am not able to run the project in my local machine due to various dependency issues and the miniconda installation file that is present in the readme.md

**Comment by yochannah** [comment]
@devil-cyber I feel for you, resolving dependencies can be a real pain sometimes 😭 I have a couple of suggestions: 

1. you could try sharing the errors and we could try to help your troubleshoot
2. you could try enabling github pages for your fork of the repo and try testing your code that way

If you'd rather put this task down and let someone else pick it up that's fine too - whatever your preference :)

**Comment by devil-cyber** [comment]
Ok i will share the issue 😀

**Comment by yochannah** [comment]
okay - this issue is open for any contributor to pick up again :)

**Comment by NPDebs** [comment]
Hi @yochannah 👋🏼 Is this issue still up for grabs? 😃 👀

**Comment by Abiola-Zeenat** [comment]
hello @yochannah , I am an outreachy applicant and would love to make a contribution to this

**Comment by bebatut** [comment]
As defined in the [OLS Outreachy contribution guide](https://docs.google.com/document/d/1HP7qTBe-6YrCUYAVkrT441rGtF6zxzNbbz2E5RWQvTM/edit?usp=sharing),

- If someone else has already commented, let them try first
- If they don’t update after three days, the issue is “free” again, and you can pick it up.

@NPDebs were the first one to comment here, but is already assigned to other issues. 
@Abiola-Zeenat  Are you  interested to work on this issue?

**Comment by tnwoodard** [comment]
Hi @bebatut.  I am an Outreachy applicant and would like to be added to the queue if the issue becomes free again.  Thanks!

**Comment by NPDebs** [comment]
> > 
> 
> yes @bebatut ,I am interested to work on this issue but if it has been assigned,i can try looking out for other issues else i would like to try it out if it comes up again

@Abiola-Zeenat I don't think this has been assigned to anyone. I was going to work on it but got assigned somewhere else.

You can definitely take this on, girl!

**Comment by Abiola-Zeenat** [comment]
> > > 
> > 
> > 
> > yes @bebatut ,I am interested to work on this issue but if it has been assigned,i can try looking out for other issues else i would like to try it out if it comes up again
> 
> @Abiola-Zeenat I don't think this has been assigned to anyone. I was going to work on it but got assigned somewhere else.
> 
> You can definitely take this on, girl!

okay, I'll jump on it then, thanks.

**Comment by Abiola-Zeenat** [comment]
Hi @bebatut, I made a PR on this. Kindly review.

**Comment by bebatut** [comment]
Anyone else here interested to review @Abiola-Zeenat  PR? Please have a look here #442

**Comment by NPDebs** [comment]
> Anyone else here interested to review @Abiola-Zeenat PR? Please have a look here #442

Sure! I'll have a look.

**Comment by tnwoodard** [comment]
Hi @NPDebs and @Abiola-Zeenat. I'd like to review the pull request if it hasn't been yet.  Thank you.

**Comment by NPDebs** [comment]
Hi @tnwoodard. 👋🏼😃
The initial PR was in the process of being reviewed.
Our mentor had provided an alternative method of adding the required feature. We haven't heard from @Abiola-Zeenat since then. 👀

**Comment by tnwoodard** [comment]
Thanks for letting me know. I’m here to help if needed. Take care! 👋🏾

**Comment by yochannah** [comment]
I'm closing this as out of date - thanks for the contribution!
