### ISSUE TITLE
tools: project management for OLS

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/open-life-science.github.io#222]
Options to choose from:

- Asana (B2B production)+GDrive+GitHub = can be managed by Zapier (often free)
- Slab (offload things from google drive) and Notion (all integration, templates+database, online, cheap - works with Zapier)
- End platform: Trello, Asana (both free and paid work fine, 5 email addresses are needed to open a team), Jira (paid)

**Comment by yochannah** [comment]
github :)
