### ISSUE TITLE
Add legal status to website

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#227]
we get a lot of enquiries about our legal status, we should add a note (to the footer?) that we are a legal entity. Something like:

> Open Life Science Limited is a non-profit charitable company limited by guarantee, based in the United Kingdom. Company number: 12824090

**Comment by merrcury** [comment]
I guess this can be closed.

**Comment by bebatut** [comment]
Nice catch @merrcury. Thanks! I close this issue
