### ISSUE TITLE
Create a separate page for collaborators, sponsors and partner

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/open-life-science.github.io#233]
Create a separate page that has the following sections:

- Collaborators
- Sponsors
- Partners

Think about how we indicate their support for different rounds.

**Comment by alvinokafor** [comment]
Hi @malvikasharan, I am an outreachy intern amd i would love to work on this issue

**Comment by Jolah1** [comment]
Hello @bebatut 
My name is Jolade, I am an Outreachy applicant, I will be working on this issue.
thank you.

**Comment by bebatut** [comment]
Thank you for your interest. Such pages exist already. We forgot to close this issue
