### ISSUE TITLE
Tooling - call hosting documents? 

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#26]
Some suggestions: 
- Etherpad (e.g. from the carpentries or software freedom conservancy - slightly problematic that we don't have our own) 
- HackMD (My preferred choice, works nicely for Whitaker Lab calls but is there a learning curve?)
- Google Docs

@malvikasharan @bebatut what do each of you prefer? I'm fine with any but like HackMD the best of all the options- it's collaborative, easy to insert names, easy to see who edited what, and does have WYSIWYG controls at the top if people don't know markdown. It's also a nice sneaky way to _teach_ people markdown by doing.

**Comment by malvikasharan** [comment]
here is a European Etherpad: https://yourpart.eu. I like Etherpad and Google doc quite a lot (ore than hackMD), google doc is a bit more anonymous and easy to keep track of.

My preference will be for google doc.

**Comment by yochannah** [comment]
Okay - spoke to @bebatut - she agrees that Google Docs is easier :) Google Docs it is
