### ISSUE TITLE
Adjust the description of the project on the website 

### ISSUE THREAD

**Issue by BatoolMM** [open-life-science/open-life-science.github.io#270]
Do you mind if I submit a PR to make a few changes and add more details about the description of my project on the website?

**Comment by bebatut** [comment]
Hi @BatoolMM,

Sure. Feel free to submit a PR with changes to the description of your project.
You can make the changes to this [file](https://github.com/open-life-science/open-life-science.github.io/blob/master/_data/ols-3-projects.yaml)

Thanks for doing that!

**Comment by BatoolMM** [comment]
Thank you @bebatut ⭐
