### ISSUE TITLE
Mailing lists? 

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#28]
- [ ] pick a mailing list tool. Ideally an openish one that doesn't track people loads.

Things we may want lists for: 

- [ ] public/general for people to hear when applications open
- [ ] eventually we'll want ones for ...
   - [ ] mentors
   - [ ] experts
   - [ ] mentees

**Comment by malvikasharan** [comment]
The carpentries uses Discuss mailing list which seems to work quite well. Not sure if there is a cost for that.

**Comment by yochannah** [comment]
Some options - 

- google groups
- mailman (requires hosting)
