### ISSUE TITLE
Add speakers without associating to slide decks?

### ISSUE THREAD

**Issue by emmyft** [open-life-science/open-life-science.github.io#292]
For some cohort calls (e.g. week 13's social call, and week 12's open leadership call), speakers don't necessarily have slide decks, but we'd still like to acknowledge them.

Currently, in `ols-3-schedule.yaml`, `speaker` is an attribute of resources `type: slides` and gets automatically added to the [list of cohort call speakers](https://openlifesci.org/ols-3#speakers-during-cohort-calls). Can we add just standalone speakers to calls?

**Comment by bebatut** [comment]
It is possible to do by just not adding the link to the slide deck. I did it for OLS-1: https://github.com/open-life-science/open-life-science.github.io/blob/a2db6d85e2b5597e836b46ab214ae0c6c55165ac/_data/ols-1-schedule.yaml#L580

(ok, I know that the category `slides` does not make sense here then...)

**Comment by bebatut** [comment]
I close this issue. @emmyft feel free to reopen if you think it is still an issue
