### ISSUE TITLE
OLS project ideas for folks joining without a personal/planned project

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/open-life-science.github.io#297]
## Don't have a project but want to join OLS-4? Here is what you should do.

1. Contact the OLS team by emailing team@openlifesci.org
2. Go through the following project ideas that you can take a lead on

### Project ideas

- [x] Visualisation of participants by their countries
- [x] Visualisation of participants who take on different roles in later rounds
- [x] Data analysis of surveys: Mid and post cohort surveys
- [ ] Review documentation of OLS workflow: what is missing? what should be added?
    - https://github.com/open-life-science/open-life-science.github.io/pull/296/files
- [ ] OLS history, progress and impact page on the website
- [ ] Curating good resources for OLS participants (funding, skills development etc.)
- [ ] FAIR-ification of training materials (metadata, GitHub repo, Zenodo releases)
- [ ] Review open issues in this repository and propose a related project (website, program, workflow, transparency etc.)

**Comment by yochannah** [comment]
Closing this issue down for now. Many of the issues have been tackled, and new issues can be added here: https://github.com/open-life-science/project-ideas
