### ISSUE TITLE
OLS-4 Dates are inconsistent

### ISSUE THREAD

**Issue by tnabtaf** [open-life-science/open-life-science.github.io#302]
This [OLS-4 page](https://openlifesci.org/ols-4#timeline) says

> OLS’s **third** cohort (OLS-4) will be conducted from **February to May 2021.**

Which, just ain't right.

**Comment by malvikasharan** [comment]
Thank you so much @tnabtaf. This PR should fix it: https://github.com/open-life-science/open-life-science.github.io/pull/303
