### ISSUE TITLE
OLS-4 Week 01 Issues links to OLS-3 

### ISSUE THREAD

**Issue by CBolibaugh** [open-life-science/open-life-science.github.io#313]
The Week 01 [page](https://openlifesci.org/ols-4/schedule/#week-01), section **After the call**, directs mentees to the OLS-3 Issues (instead of what I guess should be OLS-4), in the following:

- Create an issue on the [OLS-3 GitHub ](https://github.com/open-life-science/ols-3/issues/new)repository for your OLS work and share the link with your mentor

**Comment by emmyft** [comment]
Thank you so much for spotting this @CBolibaugh! Would you be OK to amend this and make a pull request to fix it? I can review the pull request and merge afterwards (please don't worry if this is too much hassle!) 

The OLS-4 issues page is here: https://github.com/open-life-science/ols-4/issues
