### ISSUE TITLE
[OLS-4 Cohort call week 8]

### ISSUE THREAD

**Issue by da5nsy** [open-life-science/open-life-science.github.io#329]
1. Weekly emails
   - [ ] Send email to mentees
   - [ ] Send email to speakers
2. Cohort call video preparation
   - [x] Download from Zoom cloud recordings
   - [x] Upload to Otter.ai (_will need a few minutes to process_)
   - [x] Upload to the OLS YouTube account
   - [x] Create a front page slide for the video - templates are available in Google Drive
   - [x] Make sure the YouTube video is added to the current cohort playlist
   - [x] Correct Otter.ai transcripts (_make sure to use uploaded video, not the original transcript, as the timings won't match the video_)
   - [x] Download corrected transcript as a .srt file from Otter
   - [x] Upload it to the YouTube video
   - [x] Post a link to the recording in the OLS Slack! 🙌
   - [ ] Update the schedule sheet
       - [ ]  Add link to recording
       - [ ]  Add names of hosts and faciliators
       - [ ]  Add speaker names in "Confirmed speaker"
       - [ ]  Check links to slide deck
       - [ ]  Check "Before" and "After"
       - [ ]  Post on OLS Slack that the sheet has been updated
3. Website (in schedule in `_data` folder)
   - [ ] Run script to update schedule
   - [ ] Add person detail if needed to `people.yaml` if needed

**Comment by emmyft** [comment]
I updated the to-do list here manually- the "permanent" change is pending #323 :)

**Comment by da5nsy** [comment]
OK - I think I've done everything I was meant to do here. Can someone confirm? 😃

**Comment by emmyft** [comment]
Looks good - thanks @da5nsy !
