### ISSUE TITLE
Choose application platform

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#33]
My vote is with Easychair - it's free, will be familiar to many of our applicants, and allows mentors / "reviewers" to indicate conflicts of interest clearly. 

My next best preference would be google docs :) apply on a google form, make notes and selections in a spreadsheet

**Comment by bebatut** [comment]
Easychair sounds good. Did one of you already use it as organizer? Was it ok?
Is it for free?

**Comment by yochannah** [comment]
yes, yes, and yes! :)

**Comment by yochannah** [comment]
closing this on the assumption it'll be easychair
