### ISSUE TITLE
List of announcement post for the end of 2021

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/open-life-science.github.io#336]
- [x] OLS-4 grad and OLS-5 application call
- [ ] OLS communication docs (presentations, flyers, report etc)?
- [ ] Wellcome funding to OLS, upcoming job, plans, link to application form
- [ ] Annual report 2021
- [ ] microgrant, policy, board, governance, finance update?

**Comment by bebatut** [comment]
@malvikasharan can you close this issue?

**Comment by bebatut** [comment]
Feel free to reopen it if needed @malvikasharan
