### ISSUE TITLE
UI to fix on website


### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#337]
- [ ] blog post

![Screenshot_20211206-200633.png](https://user-images.githubusercontent.com/1842467/144906974-082c35c4-790e-4238-9ef1-537ab89df8c3.png)
 
- [x] drop down menu for previous OLS

**Comment by kryptosjay** [comment]
Hi @bebatut ,
I am an outreachy applicant and would like to work on this issue.

**Comment by alvinokafor** [comment]
Hi @bebatut, I would love to work on this issue

**Comment by Neroogod** [comment]
Hello @bebatut @yochannah ..I'm an Outreachy 2022 Applicant ,I'd like to help fix this issue.

**Comment by kosonyemedaniella** [comment]
hello @bebatut @yochannah i am an outreachy applicant and i'ld like to help fix this issue

**Comment by Chalcedony219** [comment]
Hello @yochannah @bebatut 
I am Nancy, a UX designer, contributing for Outreachy. I’ll absolutely love to work on this task. Thank you

**Comment by Bisola15** [comment]
HI @bebatut, I'm an outreachy applicant. I would like to work on this task 🤲🏾 Thank you

**Comment by Ososeomo** [comment]
Hi @bebatut I am an outreachy applicant, I would like to work on this issue as a Ux designers, I'm great for this task

**Comment by Bisola15** [comment]
Hi @bebatut It's been three days since last comment on interest, so I assume the issue is free again as given in the guideline. I have some UI I made for this and I will drop them now. Thank you 😊

**Comment by Bisola15** [comment]
![OLS-5](https://user-images.githubusercontent.com/81020434/195497211-22a220b5-e5f7-4d18-81b0-2c0e7b610c44.png)
![OLS-5](https://user-images.githubusercontent.com/81020434/195497214-28f46e30-79e2-4986-b4e4-bdbb72d68b07.svg)

This is a first sample. I noticed it was an android mobile view so I followed suit. I did a little redesign of the banner is that alright  and fixed the alignment issue. Feedbacks are highly welcomed.

**Comment by Bisola15** [comment]
![OLS-5 sample 2](https://user-images.githubusercontent.com/81020434/195498458-ea36070e-45cd-475d-a342-3f5f0340bfec.png)
![OLS-5 sample 2](https://user-images.githubusercontent.com/81020434/195498475-8518ed47-8213-4a8b-9434-bada5ec8ed8b.svg)

This is the second sample

**Comment by DOC-ELIJAH** [comment]
Hi! Good job Bisola.
The second sample is still within the confines of the design theme which is cool. On the other hand, the first sample is catchy and compliments the dominant theme of the website.

@bebatut  I'd love to implement this once it's been reviewed and approved. 😊

**Comment by bebatut** [comment]
Thanks for the suggestion here.
I did not realize before but this issue is redundant with #238. And @NPDebs proposed a fix here in #449 
Feel free to review @NPDebs' PR
