### ISSUE TITLE
Bug: something is wrong in a page

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/open-life-science.github.io#344]
Core error in this page: https://openlifesci.org/ols-4/projects-participants/
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/5370471/151021999-0d3c94be-ded3-4e0e-a675-a72ee3ddfd71.png">

**Comment by bebatut** [comment]
It is not really an error. It is part of the description of their project

**Comment by malvikasharan** [comment]
Lol, should have read it clearly, I was browsing around and assumed that it's an error :D
