### ISSUE TITLE
[Broken Link][Get Involved-Roadmap]

### ISSUE THREAD

**Issue by sara-02** [open-life-science/open-life-science.github.io#37]
The hyperlink of the `roadmap` mentioned under the [get involved](https://openlifesci.org/about#get-involved) section of the website returns a 404.
Current Roadmap hyperlink: https://github.com/open-life-science/open-life-science.github.io/blob/master/roadmap.md

**Comment by sara-02** [comment]
Maybe it can be directed to #34 for the time being to a new project board here: https://github.com/open-life-science/open-life-science.github.io/projects

**Comment by bebatut** [comment]
Thanks @sara-02 for reporting this broken link. As you suggested, I replaced it by a link to the project board
