### ISSUE TITLE
Update funders, partners and team info

### ISSUE THREAD

**Issue by emmyft** [open-life-science/open-life-science.github.io#376]
imao important to live our values of transparency and openness! 

- Update our funders and partners page: https://openlifesci.org/funders 
  - add a list of past funders
- Add a new "team" page (alternative title welcome!), to have info on our organizing team members and staff.

Maybe something for the documentation sprint?

**Comment by malvikasharan** [comment]
Added CZI.
need to include Wellcome in July.

**Comment by bebatut** [comment]
It would be completely fixed by #412
