### ISSUE TITLE
Decide question for the application

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/open-life-science.github.io#38]
Add the questions from the MOL7 and collecte a few example.

**Comment by yochannah** [comment]
I couldn't find the OL7 questions, but after some digging I found the OL4 application form which appears to still be open (lol). 

It actually had quite a lot of questions - I've slimmed it down a little - my draft is in the applications folder in the root of our shared drive.

**Comment by bebatut** [comment]
All questions are in the Google doc (as a possible template for applicants)
