### ISSUE TITLE
Rubric for selection

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/open-life-science.github.io#39]
Berenice will add from her last review

**Comment by bebatut** [comment]
The document (named "Application review rubric") is in the Gdrive folder in folder "Application"

**Comment by yochannah** [comment]
This looks great to me!

**Comment by bebatut** [comment]
It was approved yesterday by both @malvikasharan and @yochannah. Feel free to reopen the issue if you want to discuss more about it
