### ISSUE TITLE
Wrong cohort numbering under OLS-X for Turing heading

### ISSUE THREAD

**Issue by amangoel185** [open-life-science/open-life-science.github.io#392]
The cohort numbering from under the heading “OLS-X for Turing” is stuck on “third” since OLS-3. The issue exists in [`ols-4.md`](https://github.com/open-life-science/open-life-science.github.io/blob/5d4d1e9862c7fcd1950f37e7680ad37a16393947/ols-4.md?plain=1#L297), [`ols-5.md`](https://github.com/open-life-science/open-life-science.github.io/blob/5d4d1e9862c7fcd1950f37e7680ad37a16393947/ols-5.md?plain=1#L298), [`ols-6.md`](https://github.com/open-life-science/open-life-science.github.io/blob/5d4d1e9862c7fcd1950f37e7680ad37a16393947/ols-6.md?plain=1#L297), [`ols-7.md`](https://github.com/open-life-science/open-life-science.github.io/blob/5d4d1e9862c7fcd1950f37e7680ad37a16393947/ols-7.md?plain=1#L297) and [`ols-8.md`](https://github.com/open-life-science/open-life-science.github.io/blob/5d4d1e9862c7fcd1950f37e7680ad37a16393947/ols-8.md?plain=1#L297).

Should the cohort numbering be in words (fifth, sixth etc.) or numerical (5th, 6th etc.)? I can open a PR to fix the same.

**Comment by yochannah** [comment]
Thanks @amangoel185 !! Please do open a PR, that would be awesome! I have no strong feelings about fifth vs 5th, whatever's easiest?

**Comment by amangoel185** [comment]
Great, sure!
