### ISSUE TITLE
[OLS-5] Add missing details about the facilitators

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/open-life-science.github.io#407]
Currently we have a host section in each cohort but many names are missing.

Instead of host we should create 'facilitator' section and add missing names (e.g. Mayya, Mike ...)

**Comment by bebatut** [comment]
It will be fixed by #412

**Comment by kryptosjay** [comment]
Hi @bebatut ,
I am an outreachy applicant and would like to work on this issue.
if given access please

**Comment by ricMbugua** [comment]
Hi @bebatut  my name is Richard and would love to fix this issue for you. Am ready to work on it any time.

**Comment by bebatut** [comment]
The issue was fixed already. Thanks for the asking to help there

**Comment by ricMbugua** [comment]
Okay thank you.

**Comment by ricMbugua** [comment]
If anymore changes are needed please let me know.
