### ISSUE TITLE
Move Code of Conduct to policy GitHub repo

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#414]

**Comment by baimamboukar** [comment]
Hello @bebatut ! I am a Outreachy applicant! I already raised a pull request for this issue 
https://github.com/open-life-science/policies-procedures-and-docs/pull/13

**Comment by bebatut** [comment]
Thanks @baimamboukar for this contribution.
We then need to replace the Code of Conduct from this repository and on the website with a link to the one in the Policy folder

**Comment by baimamboukar** [comment]
Alright ☄️
I'm doing it....
I will soon raise a pull request

**Comment by baimamboukar** [comment]
Hi @bebatut ! I think the frist pull request should be merged so that I can get the link of code_of_conduct in the policies repository!

Or any other way I can do it ?

**Comment by baimamboukar** [comment]
@bebatut Thanks for assigning me the issue! 
You said I should replace the conde-of-conduct of this repository with a link to the one in policies repository! Right ?

But there is no any CODE_OF_CONDUCT.md file in policies repository! The pull request I raised (https://github.com/open-life-science/policies-procedures-and-docs/pull/13) has not been merged yet!
Or there is any other way I can continue workin on this without ? I am little bit confused

Thanks for your feedbacks in advance...

**Comment by bebatut** [comment]
It is merged now

**Comment by baimamboukar** [comment]
> It is merged now

Thanks....
I will finish the task very soon ☄️

**Comment by baimamboukar** [comment]
Hello @bebatut ! I'm a little bit confused about this...

I saw that the ``CODE_OF_CONDUCT.md`` in the website repo has been used here (``code-of-conduct.md``) like so ```{% include CODE_OF_CONDUCT.md %}```

![image](https://user-images.githubusercontent.com/49169158/195050390-b7373faa-3a40-4d93-bb03-786503efed28.png)


### I'm wondering if replacing the content of ```CODE_OF_CONDUCT.md``` file with a link to this ``https://github.com/open-life-science/policies-procedures-and-docs/blob/c342530ffe943bcc1a84a1a8a8e3b5b3c0fa4547/CODE_OF_CONDUCT.md``  will not affect the ```include``` operation in ``code-of-conduct.md`` file

**Comment by bebatut** [comment]
You need to change in the navbar directly, and remove the `code-of-conduct.md` file then

**Comment by baimamboukar** [comment]
Alright ☄️

**Comment by baimamboukar** [comment]
> You need to change in the navbar directly, and remove the `code-of-conduct.md` file then
Already done ✅🎉
I applied these modifications here 🚩 #447
