### ISSUE TITLE
Add a proper Table of Content for the syllabus pages

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#415]

**Comment by Hauwarh** [comment]
Hi @bebatut 
I'm an outreachy Intern, can I be assigned this issue.

**Comment by Juxtathinkacode** [comment]
Hello. I am Gimbiya, an Outreachy applicant and content writer. Please assign me this task.

**Comment by iremide1022** [comment]
Hello I’m dorcas, an outreachy applicant can I be assigned to this task

**Comment by Munnachienyi** [comment]
@bebatut, what should be in the table of content because it's currently empty? could you explain, please?

**Comment by bebatut** [comment]
The table of content should contain the different headers. It should be automatically created

**Comment by Juxtathinkacode** [comment]
Ok.

**Comment by NPDebs** [comment]
@bebatut 👀 May I please be assigned this issue? 🙏

**Comment by NPDebs** [comment]
Thanks @bebatut.
I've marked the PR as **_ready for review_**.

**Comment by bebatut** [comment]
Fixed with  #682
