### ISSUE TITLE
Make UTC for schedule on OLS-6 page, not CET

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#416]
Change to a more neutral timezone. Tell @pazbc  about this

**Comment by bebatut** [comment]
To do that
- Change the Jekyll template for schedule
- Modify the timing in all schedule files (in `_data` folder)

**Comment by NPDebs** [comment]
Hi @bebatut. 👋🏼 
Can I please work on this?

**Comment by dipanshuraz** [comment]
Hi @bebatut , I'm an outreachy applicant, and I'm interested in working on it. Please assign this to me

**Comment by bebatut** [comment]
I assign this issue to you @dipanshuraz
