### ISSUE TITLE
GitHub action with Cron job to automatically update schedule 

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#419]
The website need to be regularly updated with information about the cohort calls during a cohort.
To do the update, I currently run manually from time to time a script as explained here: 
https://github.com/open-life-science/open-life-science.github.io#update-schedule-for-a-cohort

It would be nice to have script running as a Cron job on GitHub action.

**Comment by bebatut** [comment]
I added details about the idea there. Let me know if you have any question

**Comment by baimamboukar** [comment]
Hello @bebatut ! 
I have been reading about setting up github actions workflows to run cron jobs!
I am already working on this....

**Comment by baimamboukar** [comment]
What is the frequency of triggering the cron job? Every 3 months ?

**Comment by baimamboukar** [comment]
Hello @bebatut !
I raised a [pull request](https://github.com/open-life-science/open-life-science.github.io/pull/440) #440 about this issue!


### Thanks for reviewing!
I'm waiting for feedbacks...

**Comment by yochannah** [comment]
this issue is complete.
