### ISSUE TITLE
Header image and hidden navbar on small screen

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#420]
![Screenshot_20220916-213716.png](https://user-images.githubusercontent.com/1842467/190717507-421b8430-a8b0-4eb5-a2b4-94072a522188.png)

**Comment by abitsalihu** [comment]
@bebatut I would like to work on this issue. :)

**Comment by NPDebs** [comment]
Hi @bebatut .
I'd love to work on this issue, please. 👍🏻

**Comment by kryptosjay** [comment]
I'd love to work on this project if given access to it thank you

**Comment by Neroogod** [comment]
Hello @bebatut ,I'm an outreachy 2022 Applicant,I'd love to work on this issue.

**Comment by xiaodaiweiwei** [comment]
Hello @bebatut , I'm Astrid Liu and I'm an outreachy applicant. I'd love to work on this issue. Thank you!

**Comment by Chalcedony219** [comment]
I’ll love to work on this issue @bebatut 
My name is Nancy (an Outreachy applicant), a UX designer. Thank you

**Comment by Jolah1** [comment]
hello @bebatut my name is Jolade, an outreachy applicant, I am currently working on this issue. Thank you

**Comment by Jolah1** [comment]
Got it! Thank you so much.

**Comment by NPDebs** [comment]
> As defined in the [OLS Outreachy contribution guide](https://docs.google.com/document/d/1HP7qTBe-6YrCUYAVkrT441rGtF6zxzNbbz2E5RWQvTM/edit?usp=sharing), 
> - If someone else has already commented, let them try first
> - If they don’t update after three days, the issue is “free” again, and you can pick it up. 
> 
> @NPDebs were the first one to comment here. Are you still interested to work on this issue?

Yes, please. @bebatut Thank you! 😊

**Comment by NPDebs** [comment]
Hi @bebatut . Here's an update on my progress.
After inspecting this page for some hours, I realised that the problem is not just about the header. The entire page displays abnormal behaviour (excess space on the right) when the viewport width hits 570px.

This is caused by the <table> section, which overflows from the body. Adjusting the table will result in the expected behaviour.

**Comment by NPDebs** [comment]
@bebatut I think you forgot to close this issue. 👀

**Comment by bebatut** [comment]
Nice catch
