### ISSUE TITLE
 LICENSE update: Add MIT license for infrastructure / scripts

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#421]
Our current CC-BY-SA 4.0 license does not make possible to reuse the infrastructure and scripts

Solution
- Change the LICENSE file to MIT here
- Make sure that CC-BY-SA 4.0 (for content) is mentioned on the README, and on the website

**Comment by Jolah1** [comment]
Hello @bebatut 
My name is Jolade, I am an Outreachy applicant, I will be working on this issue.
thank you.

**Comment by bebatut** [comment]
Thanks @Jolah1 for you interest. @oluwatobiBolu started to work on this issue here #427
Would you like to review the changes?
