### ISSUE TITLE
Typos in README

### ISSUE THREAD

**Issue by NPDebs** [open-life-science/open-life-science.github.io#428]
**Current behavior:** I noticed some typos in the README of this repo.

![ols-readme-issue (2)](https://user-images.githubusercontent.com/105166953/194860856-5b7f29a7-8166-40c7-b427-15bffa00d338.png)

**Expected behavior:** The file should be edited to correct this.

**Comment by NPDebs** [comment]
@yochannah & @bebatut 
I noticed these typos and raised a "good first issue" which can be fixed by any of my fellow Outreachy participants.

I'm available to work on it if no one else indicates interest. Thanks!

**Comment by bebatut** [comment]
Looks good!

**Comment by Valliammai-SM** [comment]
Could you assign this to me?

**Comment by NPDebs** [comment]
> 

Thank you kindly!

I just noticed that the entire file might need a bit of editing for similar issues.
What do you think would be the best approach to tackling this?
1. Create individual, bite-sized issues for each typo I spot. (So that everyone gets a chance to contribute)
2. Raise a PR that addresses all the errors at once. (To make things faster)

@bebatut  & @yochannah

**Comment by NPDebs** [comment]
> @NPDebs do you want to work on it? Or @Valliammai-SM should do?

Love the enthusiasm! Please assign it to @Valliammai-SM Thank you!

**Comment by NPDebs** [comment]
> > > 
> > 
> > 
> > Thank you kindly!
> > I just noticed that the entire file might need a bit of editing for similar issues. What do you think would be the best approach to tackling this?
> > ```
> > 1. Create individual, bite-sized issues for each typo I spot. (So that everyone gets a chance to contribute)
> > 
> > 2. Raise a PR that addresses all the errors at once. (To make things faster)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @bebatut & @yochannah
> 
> The 2nd proposition would be probably better

Awesome! I'll be opening a PR soon. Thank you!

**Comment by NPDebs** [comment]
@bebatut Thank you for merging.

A subtle reminder to mark this issue as closed, please. 😃 Thank you.
