### ISSUE TITLE
Write and publish blog post with Emmy

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#43]

**Comment by yochannah** [comment]
https://docs.google.com/document/d/1EkFK5rcK2j-8e3nneQVGljMGhZJpRijX80osGcCmesc/edit

**Comment by yochannah** [comment]
Live here: https://www.open-bio.org/2019/11/12/supercharge-your-open-project-with-leadership-training/

We're also trying to cross-post with the SSI
