### ISSUE TITLE
Stories page: alignment or redesign?

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#433]
In the current stories page, each story comes with a image and a title. But they do not really aligned:

![image](https://user-images.githubusercontent.com/1842467/194878263-e54cc9e1-4cab-4cef-b99b-c37b423bdb35.png)

It might be good to aligned them or change a bit the layout of this page

**Comment by jilaga** [comment]
> i would like to work on this

> @oluwatobiBolu how about rearranging the layout of the card?

**Comment by jilaga** [comment]
> > i would like to work on this
> 
> > @oluwatobiBolu how about rearranging the layout of the card?

![OLS stories card](https://user-images.githubusercontent.com/105386444/194899216-dc390230-fe4b-49ec-a40f-09e9bc290eec.png)

**Comment by jilaga** [comment]
> > > i would like to work on this
> > 
> > 
> > > @oluwatobiBolu how about rearranging the layout of the card?
> 
> ![OLS stories card](https://user-images.githubusercontent.com/105386444/194899216-dc390230-fe4b-49ec-a40f-09e9bc290eec.png)

In this approach, contents don't spill out of their assigned positions.

**Comment by oluwatobiBolu** [comment]
> > > > i would like to work on this
> > > 
> > > 
> > > > @oluwatobiBolu how about rearranging the layout of the card?
> > 
> > 
> > ![OLS stories card](https://user-images.githubusercontent.com/105386444/194899216-dc390230-fe4b-49ec-a40f-09e9bc290eec.png)
> 
> In this approach, contents don't spill out of their assigned positions.

yeah
this is the approach i plan on taking so the contents don't look out of place when comparing the stories with eachother

**Comment by oluwatobiBolu** [comment]
@jilaga are you working on it already?

**Comment by jilaga** [comment]
> @jilaga are you working on it already?

> nice to know we have a similar approach. When I saw the issue, I jumped to sketch a proposed solution. I do design and don't know so much about dev like you so you could just implement the sketch in your gitpod and pull a request.

**Comment by jilaga** [comment]
> > @jilaga are you working on it already?
> 
> > nice to know we have a similar approach. When I saw the issue, I jumped to sketch a proposed solution. I do design and don't know so much about dev like you so you could just implement the sketch in your gitpod and pull a request.

@oluwatobiBolu I'm just happy to help

**Comment by oluwatobiBolu** [comment]
it's a nice design, i will be trying it out
thanks for the help

**Comment by jilaga** [comment]
> it's a nice design, i will be trying it out thanks for the help

> thanks for letting me help!

**Comment by bebatut** [comment]
@oluwatobiBolu opened a Pull Request here #441. Anyone wants to review it?

**Comment by JulianaSau** [comment]
Hi @bebatut. I'd like to review the pr

**Comment by iremide1022** [comment]
I would love to work on this🙏 @bebatut

**Comment by bebatut** [comment]
@iremide1022, @oluwatobiBolu worked on this issue and opened a Pull Request #441 . You can review it if you want

**Comment by iremide1022** [comment]
@oluwatobiBolu and @jilaga nice work you have got here!

**Comment by Chimatara** [comment]
Hi @oluwatobiBolu can I message you on slack?

**Comment by oluwatobiBolu** [comment]
> Hi @oluwatobiBolu can I message you on slack?

sure
i'm oluwatobi adelakun on slack

**Comment by Chimatara** [comment]
Thank you @oluwatobiBolu

**Comment by NPDebs** [comment]
Thank you all for your contributions! 🎉 
This issue has been resolved with PRs #441 and #573.
