### ISSUE TITLE
Emtpy links in people pages

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#437]
I ran [Wave](https://wave.webaim.org/) to check for accessibility on the website.
In the people pages, I got many errors because of empty links, in the people information:

![image](https://user-images.githubusercontent.com/1842467/194893874-9b4f7136-3a94-4f9b-93c0-6ac3f3589d88.png)

It would be good to fix them

**Comment by Munnachienyi** [comment]
how do we go about this @bebatut

**Comment by iLynette** [comment]
Hello, @bebatut I would like to work on this.

**Comment by bebatut** [comment]
@Munnachienyi you will need to look at the template for the people and check how to fix the empty links

**Comment by Munnachienyi** [comment]
do you mean the links to the GitHub page of the contributors

**Comment by bebatut** [comment]
I do not know which links. You can install the wave extension in your browser and activate it on the people page to see where these links are empty

**Comment by Munnachienyi** [comment]
okay, i am not familiar with wave but i would try to see it through

**Comment by tolubishops0** [comment]
Hi,
 I'd like to give this a shot!!

**Comment by bebatut** [comment]
As defined in the [OLS Outreachy contribution guide](https://docs.google.com/document/d/1HP7qTBe-6YrCUYAVkrT441rGtF6zxzNbbz2E5RWQvTM/edit?usp=sharing), 
- If someone else has already commented, let them try first. Here @Munnachienyi seemed interested so is assigned to the issue
- If they don’t update after three days, the issue is “free” again, and @tolubishops0, you can pick it up.

**Comment by Munnachienyi** [comment]
hello, @bebatut am I to delete the empty links? thanks for assigning this issue to me

**Comment by Njong392** [comment]
> and I can't really find the people|OLS. I navigated through the people HTML,i really don't understand

In the `layouts` folder you'll find the `people.html` file you need to work on :+1:

**Comment by Njong392** [comment]
> I ran [Wave](https://wave.webaim.org/) to check for accessibility on the website. In the people pages, I got many errors because of empty links, in the people information:
> 
> ![image](https://user-images.githubusercontent.com/1842467/194893874-9b4f7136-3a94-4f9b-93c0-6ac3f3589d88.png)
> 
> It would be good to fix them

@bebatut When you say empty links here I don't quite get it. I ran my wave extension and it did give me the same flags. Does it mean the links are broken? or that they do not lead anywhere? Because the links work...

**Comment by Munnachienyi** [comment]
I experienced same yesterday,the link works but not all does. Some of the links points out to a  nonexistent GitHub address or Twitter handle 
What do you suggest @bebatut ?

**Comment by bebatut** [comment]
I am not sure what does the error really mean. Could you look at the documentation about this error and see how it could be fixed?

**Comment by Munnachienyi** [comment]
@bebatut I have been struggling for days now to remove broken website links, but when I run the web accessibility tool, it feels like I am doing nothing.please help

![web access](https://user-images.githubusercontent.com/105428107/195835794-b62ff021-b516-4408-a86a-fbec7dbd5dbe.png)

**Comment by bebatut** [comment]
To follow, can you explain me more in details what you did?

**Comment by Munnachienyi** [comment]
I navigated to the people.yaml file to edit, i deleted the broken website links and went ahead to run the wave extension and was greeted with the empty link.

**Comment by bebatut** [comment]
Can you open a draft Pull Request so I can have a look?

**Comment by Munnachienyi** [comment]
I tagged you in a draft pull request

**Comment by bebatut** [comment]
Thanks. I will have a look

**Comment by AndreaSanchezTapia** [comment]
Just linking here the PR: #467

**Comment by Munnachienyi** [comment]
thanks @AndreaSanchezTapia
