### ISSUE TITLE
Contrast error in schedule page

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#439]
I ran [Wave](https://wave.webaim.org/) to check for accessibility on the website.
In the [schedule page of OLS-6](https://openlifesci.org/ols-6/schedule/), I got 3 errors because of contrast:

![image](https://user-images.githubusercontent.com/1842467/194894668-3bdd44cb-8b7f-4f32-9a1f-725cbc5635f5.png)

It would be good to fix them

**Comment by Lovelyfin00** [comment]
Hi @bebatut 
Can i quickly work on this?

**Comment by bebatut** [comment]
Sure 😃

**Comment by Lovelyfin00** [comment]
@bebatut 
I'm kind of very confused. I've opened the project on gitpod. But the scheduled on the ol6 folder is a markdown file.  Where are the html files? I'm so confused. This is the first time I'm contributing to open source

**Comment by bebatut** [comment]
The Markdown are transformed into HTML using [Jekyll](http://jekyllrb.com/). 
You can find the templates for the HTML in the layouts and include folders.

**Comment by iLynette** [comment]
Hello @Lovelyfin00 if you're still confused we can look at it together, perhaps? if that's okay with @bebatut

**Comment by Lovelyfin00** [comment]
@iLynette
Yes please
Let's look at it together
Because I'm still confused
Haven't used Jekyll before
And can we talk on private
Send me a message on github please

**Comment by iLynette** [comment]
Of course @Lovelyfin00 I haven’t used Jekyll before either but I believe we can learn and solve it while at it. I’m not sure there’s an option for a private chat on GitHub though, if you are on the OLS slack channel please give me your username and I’ll directly message you. Or you can search for my name, Lynette Acholah

**Comment by Lovelyfin00** [comment]
Ok
My username is Nutjob on the slack channel

**Comment by ladyami** [comment]
hello I am aminaoyegoke for outreachy can we look at it together i just want to learn that you
I

**Comment by Chimatara** [comment]
HI @bebatut how do I get the source code for this page, I think I can work on it.

**Comment by bebatut** [comment]
The source is there: https://github.com/open-life-science/open-life-science.github.io/blob/main/_includes/detailed-schedule.md

**Comment by Chimatara** [comment]
Hi @bebatut can you please review the PR I made on this issue, here is the link  
https://github.com/open-life-science/open-life-science.github.io/pull/489/commits/c64789576b001ed5cf4c85aefcfc5ec821961b0a

![Screenshot (20)](https://user-images.githubusercontent.com/65595525/197359790-9c69868e-5501-401b-b14c-230b61461cb8.png)

**Comment by bebatut** [comment]
This was fixed in #500
