### ISSUE TITLE
Blog post / stories: tag posts with stories or news and make both accessible from navbar 

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#444]
Currently, there are blog posts / stories by mentees, mentors, and programme updates. There are all accessible via the Stories page. But if you're not familiar with the programme it is kind of difficult to distinguish between the posts.

Suggested implementation:
-  Tag posts with stories or news
- Add a dedicated page for each category and make them accessible from the navbar

**Comment by Ososeomo** [comment]
Hi @bebatut I suggest a page can be dedicated to this effect. This will increase the chances of page visitors viewing and navigating the page easily and  I think it will be easier for stories to be updates and put in an orderly form.
The Nav bar would serve a good use for this to remain user friendly

**Comment by AdeolaAdekoya** [comment]
I believe that adding more links to the nav bar may make it a little more clogged up, so I believe that tags will be the most effective. However, in the meantime, perhaps a section can be created on the home page to welcome newcomers to the community by displaying excerpts from stories and blogs. This will direct them to the stories page, where they can choose what they want to read based on the tags.

**Comment by bebatut** [comment]
The idea is to add a drop-down menu in the current "Stories" linking to both. Not adding another item in the navbar

**Comment by tolubishops0** [comment]
Hi 
Can I work on the drop-down menu, please?

**Comment by AdeolaAdekoya** [comment]
> The idea is to add a drop-down menu in the current "Stories" linking to both. Not adding another item in the navbar

Alright, this makes it more clear, thank you.

**Comment by bebatut** [comment]
As defined in the [OLS Outreachy contribution guide](https://docs.google.com/document/d/1HP7qTBe-6YrCUYAVkrT441rGtF6zxzNbbz2E5RWQvTM/edit?usp=sharing), 
- If someone else has already commented, let them try first
- If they don’t update after three days, the issue is “free” again, and you can pick it up. 

@Ososeomo   were the first one to comment here. Are you interested to work on this issue? Y

**Comment by tolubishops0** [comment]
@bebatut  Good Morning!! 
Has this issue been fixed please? 
Its been a week so far we've not seen any update in this regard

I'd like to work on this if it is still available please

**Comment by bebatut** [comment]
oluwatobiBolu opened a Pull Request here #482
@tolubishops0 you can have a look and also review :smile:

**Comment by tolubishops0** [comment]
Alright!

**Comment by yochannah** [comment]
closing this issue - out of date
