### ISSUE TITLE
Clarify the landing page

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#445]
From a community member: 

> The landing page could be a bit clearer, I would put everything not essential to the “program description” page and have more links on the landing page. For instance the program timeline figure cannot be read at normal size, so I would put it away.

We thought program timeline would help people to understand the structure of the program. But maybe it is not really helping.

Any suggestions on what could be done there?

**Comment by jilaga** [comment]
I think 'cluster' is the word. All the headings and their body on the landing page are clustered together and leave no room for breathing. 

I suggest spacing out the headings more to improve the user experience of the landing page.

Thank you.

**Comment by Ososeomo** [comment]
I agree with @jilaga users or audience find it easier to navigate pages when there isn't so much going on, if the headings are  also in certain hierarchy or order of importance, then it would make the landing page look less up tight and easy to the eyes.

**Comment by AdeolaAdekoya** [comment]
I also agree with what @jilaga and @ososeomo have said, I believe there are way too many words i which makes it hard to scan and also the text heir achy. It's hard to figure out what the most important information on the website is. I believe we could redesign it and potentailly work on developing it if thats fine

**Comment by jilaga** [comment]
> I also agree with what @jilaga and @Ososeomo have said, I believe there are way too many words i which makes it hard to scan and also the text heir achy. It's hard to figure out what the most important information on the website is. I believe we could redesign it and potentailly work on developing it if thats fine

> this! it's almost like an overload of words for a first-time user, like you're forced to settle and read in order to find your way around the website.

**Comment by Bisola15** [comment]
Taken from what everyone has said, it isn’t t so much as too much word as arrangement on the Landing page. The entire Landing page itself is not as long as lots of landing pages out there. Agreeing with @jilaga we can have more visual hierarchy on the page that enhances viewers scan-ability. 

Some information Seem to be repeated across different pages, we can have those eliminated with a clear direction to users to know where to go to find that information in a single page.

We can also go through the copies to see which of them can be reworded or represented with pictures or illustrations in a way that will make the website more animated. 

We could even have videos of facilitators or mentors and mentees at work... This can go on the stories side or as a brief introduction on the mentors and mentees section.

**Comment by Bisola15** [comment]
> I also agree with what @jilaga and @Ososeomo have said, I believe there are way too many words i which makes it hard to scan and also the text heir achy. It's hard to figure out what the most important information on the website is. I believe we could redesign it and potentially work on developing it if thats fine

Would be nice yeah... but @bebatut  said on slack today that its the job of  interns and we can only fix minor issues.

**Comment by Ososeomo** [comment]
@Bisola15 @bebatut asked for suggestions and @jilaga and I gave some suggestions based on what she asked.

**Comment by Bisola15** [comment]
> @Bisola15 @bebatut asked for suggestions and @jilaga and I gave some suggestions based on what she asked.

Hi, Oh yes I understand. I was looking at the timeline and figured it was around the time we were planning on working out some sketches. I was only bringing to notice what @bebatut  had said on slack, I apologize if that came off wrong.  I was referring to this statement... 'believe we could redesign it and potentially work on developing it if thats fine'

**Comment by kosonyemedaniella** [comment]
I agree with @jilaga and @Ososeomo i think that there should be spacing. White space is important as it allows the design to breathe and allows the users to see the all of the information. It also provides clarity.  
As for the program timeline , the typography size should be increased and a link should be provided for the program timeline to avoid clustering.

**Comment by lisaomoh101** [comment]
I agree with @jilaga and @Ososeomo  after taken time to view the landing page. I feel this where we put in place  some Laws of UX, The landing page is the first interface every use interact with when opening a webpage and it has to give users more understanding when navigating each elements on the page.
I will love to work with you guys on this issue.

**Comment by nwamakaakah** [comment]
The website itself needs a redesign. I believe that new design systems should be created putting into consideration hierarchy using sizes and colours, clear primary and secondary Call To Actions and also as every else has noted; the use of white space. Also using text width as I noticed that the texts span a certain width which makes it hard for the eye to read through.

Particularly, the area that describes different milestones and timlines should be more clear. As is, I am unable to read through and see the information, because they are clustered and also too tiny. I suggest a horizontal progress bar or a gallery like carousel that slides in and out of view vertically

**Comment by iremide1022** [comment]
I agree with this a landing page should be kept simple and quite understandable for users! When do we jump right into it @bebatut

**Comment by bebatut** [comment]
The design of the website will be something that both interns will work together on during the internship. For the contribution phase, we would prefer that you show us your technical skills as a big part of the internship will be quite technical, working on the website infrastructure with Jekyll, e.g. reduce the existing redundancy in the different templates by developing or using existing Jekyll/ruby plugins to, develop Jekyll theme for OLS which could be reused for different websites under OLS umbrella

**Comment by JulianaSau** [comment]
> From a community member:
> 
> > The landing page could be a bit clearer, I would put everything not essential to the “program description” page and have more links on the landing page. For instance the program timeline figure cannot be read at normal size, so I would put it away.
> 
> We thought program timeline would help people to understand the structure of the program. But maybe it is not really helping.
> 
> Any suggestions on what could be done there?

I think the page could use a bit more visuals. I believe when people get to the landing page, they skim through the page and a lot of wording may fail to capture their attention or elicit an intrigue for what the site is about. The timeline could be presented in a tabular manner to make the data look more organized and structured. Also, the line spacing is very small thus making the page look cluttered.
A bit more spacing could be added between the sections to create a distinction. That way the users can tell that they're now moving on to a different topic or segment of the page

**Comment by tolubishops0** [comment]
> > From a community member:
> > > The landing page could be a bit clearer, I would put everything not essential to the “program description” page and have more links on the landing page. For instance the program timeline figure cannot be read at normal size, so I would put it away.
> > 
> > 
> > We thought program timeline would help people to understand the structure of the program. But maybe it is not really helping.
> > Any suggestions on what could be done there?
> 
> I think the page could use a bit more visuals. I believe when people get to the landing page, they skim through the page and a lot of wording may fail to capture their attention or elicit an intrigue for what the site is about. The timeline could be presented in a tabular manner to make the data look more organized and structured. Also, the line spacing in the paragraphs is very small thus making the page look cluttered. A bit more spacing could be added between the sections to create a distinction. That way the users can tell that they're now moving on to a different topic or segment of the page

I believe she said the interns would work on the redesign once they get in

**Comment by yochannah** [comment]
this applied to the previous homepage which has now been redesigned. Thanks all!
