### ISSUE TITLE
Page header not taking full width for mobile sizes.

### ISSUE THREAD

**Issue by Etang-ken** [open-life-science/open-life-science.github.io#448]
On the OLS website, some page headers are not taking full width when reduced to mobile size. This is specifically for pages that have contents overflow that exceeds screen width e.g the home and resource pages.

![Screenshot (134)](https://user-images.githubusercontent.com/80832445/195140515-326ab288-a7e6-41ed-b541-9c298576faff.png)
![Screenshot (133)](https://user-images.githubusercontent.com/80832445/195140504-00f437f3-4a3e-4488-9926-c77b92327b45.png)

@bebatut , Please I will like to work on this issue.

**Comment by tolubishops0** [comment]
Hi bebatut,
could I get a shot to work on this pleaseee???

**Comment by laskelly** [comment]
@Etang-ken 
I think this issue has already been opened here.
https://github.com/open-life-science/open-life-science.github.io/issues/420

**Comment by NPDebs** [comment]
> On the OLS website, some page headers are not taking full width when reduced to mobile size. This is specifically for pages that have contents overflow that exceeds screen width e.g the home and resource pages.
> 
> ![Screenshot (134)](https://user-images.githubusercontent.com/80832445/195140515-326ab288-a7e6-41ed-b541-9c298576faff.png)
> ![Screenshot (133)](https://user-images.githubusercontent.com/80832445/195140504-00f437f3-4a3e-4488-9926-c77b92327b45.png)
> 
> @bebatut , Please I will like to work on this issue.

Hi @Etang-ken. 
This has already been opened (at #427).

**Comment by Etang-ken** [comment]
> > On the OLS website, some page headers are not taking full width when reduced to mobile size. This is specifically for pages that have contents overflow that exceeds screen width e.g the home and resource pages.
> > ![Screenshot (134)](https://user-images.githubusercontent.com/80832445/195140515-326ab288-a7e6-41ed-b541-9c298576faff.png)
> > ![Screenshot (133)](https://user-images.githubusercontent.com/80832445/195140504-00f437f3-4a3e-4488-9926-c77b92327b45.png)
> > @bebatut , Please I will like to work on this issue.
> 
> Hi @Etang-ken. This has already been opened (at #420).

That seems to be a different issue.

**Comment by bebatut** [comment]
This issue seems similar to this one #420. Can you comment on the #420 issue? I will close this one
