### ISSUE TITLE
Prepare email to advertize the program to send to mailing lists

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#45]
Mentioning the pre-application webinar

Which mailing list?

- [ ] SSI
- [ ] The Carpentries discuss channel (& newsletter)
- [ ] OBF
- [ ] Life Science Training slack
- [ ] Galaxy mailing list: developers, training
- [ ] de.NBI
- [ ] ELIXIR training platform
- [ ] Backofen lab
- [ ] SFBI (french bioinformatics mailing list)
- [ ] EMBL
- [ ] Turing Way newsletter

**Comment by malvikasharan** [comment]
SSI, The Carpentries discuss channel, twitter, personal invites, OBF (confirm next week), life science training slack

**Comment by bebatut** [comment]
I added few others. Feel free to edit the comment to add more
