### ISSUE TITLE
Absence of favicon when the website is ran

### ISSUE THREAD

**Issue by Munnachienyi** [open-life-science/open-life-science.github.io#450]
A favicon is used to help users visually identify websites, web pages, and web applications more easily within browser tabs, bookmarks, shortcuts, and address bars more easily.                                           

here is what I mean:

![favicon](https://user-images.githubusercontent.com/105428107/195191958-2fc9d855-cd8d-4219-a380-3c899bada145.png)

**Comment by Jolah1** [comment]
hello, I am an ouutreachy applicant, i would love to work on this issue.

**Comment by bebatut** [comment]
Thanks @Jolah1 for reporting this error.
It is something the Outreachy could work on together when rebranding will be done

**Comment by Munnachienyi** [comment]
I spotted the error @bebatut.i am also an outreachy applicant, does this mean the issue would be left open?

**Comment by bebatut** [comment]
Yes the issue will be left open

**Comment by yochannah** [comment]
this has been fixed
