### ISSUE TITLE
Create automatic releases

### ISSUE THREAD

**Issue by Njong392** [open-life-science/open-life-science.github.io#451]
I noticed that the last time there was a release, it was back in 2021. Perhaps we could create a releases.yml file that automatically updates the version based on conventional commits.

Check out conventional commits [here](https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by bebatut** [comment]
Thanks for the idea @Njong392. The best would be likely to make release at the end of every cohort, i.e. every 6 months

**Comment by Njong392** [comment]
> Thanks for the idea @Njong392. The best would be likely to make release at the end of every cohort, i.e. every 6 months

Oh okay. I opened a pull request to update the version on every commit which has the conventional style. I'll try to update the PR.

**Comment by yochannah** [comment]
closing as out of date - we have an artifact workflow now
