### ISSUE TITLE
Grammatically error on the application page on the website

### ISSUE THREAD

**Issue by Esyteck** [open-life-science/open-life-science.github.io#453]
I noticed a grammatical error while going through the application page on the website. I have highlighted the error in the attached image.
![Screenshot 2022-10-12 at 10 55 14](https://user-images.githubusercontent.com/112022744/195314998-240155da-4a30-457a-a07e-a33949c6809b.png)

**Comment by bebatut** [comment]
I am not sure to see the error here. Could you fix it directly?

**Comment by Esyteck** [comment]
Sure I can. Thanks for the opportunity

**Comment by dipanshuraz** [comment]
Hi @bebatut , I'm an outreachy applicant, and I'm interested in working on it. Please assign me

**Comment by Esyteck** [comment]
It is fixed.
