### ISSUE TITLE
Typographical error on OLS landing page

### ISSUE THREAD

**Issue by Esyteck** [open-life-science/open-life-science.github.io#454]
1. Weekly emails
  1. [ ] Send email to mentees
  1. [ ] Send email to speakers
3. Cohort call video preparation
  1. [ ] Download from Zoom cloud recordings
  2. [ ] Upload to Otter.ai (_will need a few minutes to process_)
  3. [ ] Upload to the OLS YouTube account
  4. [ ] Create a front page slide for the video - templates are available in Google Drive
  5. [ ] Make sure the YouTube video is added to the current cohort playlist
  3. [ ] Correct Otter.ai transcripts (_make sure to use uploaded video, not the original transcript, as the timings won't match the video_)
  7. [ ] Download corrected transcript as a .srt file from Otter
  8. [ ] Upload it to the YouTube video
  9. [ ] Post a link to the recording in the OLS Slack! 🙌
4. Website (in schedule in `_data` folder)
  1. [ ] Add link to recording 
  2. Add talks
      1. [ ] Add link to slide deck
      2. [ ] Add person detail to `people.yaml` if needed

**Comment by bebatut** [comment]
I do not understand what is the error here

**Comment by Esyteck** [comment]
![IMG-20221012-WA0008](https://user-images.githubusercontent.com/112022744/195344307-8fa44db1-2434-4c99-96a1-ff4c689dfc1f.jpg)

**Comment by Esyteck** [comment]
![Screenshot_20221012-133920_1](https://user-images.githubusercontent.com/112022744/195344906-3a5a721b-b98f-4342-b529-a328f0156c7e.jpg)

**Comment by bebatut** [comment]
And what is the error?

**Comment by Esyteck** [comment]
"Applications for OLS-7 will open in end 2022". I think we can modify the sentence ma'am. "Sign up to our low traffic news list to hear when the next cohort applications open". I also think we should modify the second sentence ma'am.  I think it should be "to get update on the next cohort application" I'm sorry for stressing you

**Comment by Esyteck** [comment]
"OLS-7 will open in end 2022". I think we should modify the sentence ma'am.
Secondly, "sign up to our low-traffic news list to hear when next cohort
applications open". I think we should modify the second sentence too
ma'am.

**Comment by bebatut** [comment]
> "OLS-7 will open in end 2022". I think we should modify the sentence ma'am.

How should it be modified do you think?

> "Sign up to our low traffic news list to hear when the next cohort applications open". I also think we should modify the second sentence ma'am. I think it should be "to get update on the next cohort application"

Sounds good. Please make the change :)

**Comment by Esyteck** [comment]
Got it, thanks!

**Comment by Esyteck** [comment]
Hi ma'am. Greetings from this end. After thoroughly going through the repo,
I discovered that the content to that paragraph is hidden and I do not have
access to it.

**Comment by bebatut** [comment]
The content is here: https://github.com/open-life-science/open-life-science.github.io/blob/main/index.md#applications

**Comment by Esyteck** [comment]
Hi ma'am please I humbly request for the source code so that I can have
access. Thanks

**Comment by bebatut** [comment]
I gave the link to it in my previous comment

**Comment by Esyteck** [comment]
I've fixed it. Waiting for the review. Thanks.

I hope I'm not bothering you too much?  Please Forgive my disturbance.
Hahahahaha

**Comment by AndreaSanchezTapia** [comment]
I will close this as completed.
