### ISSUE TITLE
Redesign the footer of the website

### ISSUE THREAD

**Issue by oneboyfromife** [open-life-science/open-life-science.github.io#458]
I feel we can work on the style of the footer of the website

**Comment by jilaga** [comment]
What are the changes you suggest?

**Comment by Etang-ken** [comment]
@oneboyfromife, yes true. We can re-design it and get rid of that white space in the middle.

**Comment by kamzzy** [comment]
@oneboyfromife  can i get assigned to this, am an outreachy applicant

**Comment by dipanshuraz** [comment]
Hi @bebatut , I'm an outreachy applicant, I'm interested in working on it.

**Comment by AndreaSanchezTapia** [comment]
Hi all! The interns of both projects will solve everything related to design/redesign later, while working on the rebranding. Any work today in this respect runs the risk to be overridden in the future by them. 

For now, try to find contributions that are related to the technical side of the site  ;) 

I will leave the issue open for future reference.

**Comment by iremide1022** [comment]
> Hi all! The interns of both projects will solve everything related to design/redesign later, while working on the rebranding. Any work today in this respect runs the risk to be overridden in the future by them.
> 
> For now, try to find contributions that are related to the technical side of the site ;)
> 
> I will leave the issue open for future reference.

Oh wow, noted @AndreaSanchezTapia
