### ISSUE TITLE
Contents of the Schedule image on the landing page is illegible.

### ISSUE THREAD

**Issue by jilaga** [open-life-science/open-life-science.github.io#471]
Hi, I noticed that the contents of the program's schedule diagram on the landing page are barely legible.

I had 2 ideas on how to fix this;
- Editing the source image to increase font sizes or
- creating an image modal that opens the image full screen when you click on it

**Comment by Bharlikiss** [comment]
@jilaga Are you working on this or can i be assigned to it?

**Comment by jilaga** [comment]
> @jilaga Are you working on this or can I be assigned to it?

>> I made a pull request on a solution above, you could review that for me, please? thank you

**Comment by yochannah** [comment]
this is a pre-redesign issue - closing as out of date :)
