### ISSUE TITLE
OLS-6 syllabus week-05 on website, two small fixes needed

### ISSUE THREAD

**Issue by pazbc** [open-life-science/open-life-science.github.io#473]
Hi! In the OLS syllabus for week 05 of OLS-6 (17-21 October 2022) there is something that should be deleted: "enable a small website via GitHub". And also OLS-4 should be replaced by OLS-6. It should say: "Have a look at the OLS-6 repository for project issues". The link to this repository is https://github.com/open-life-science/ols-6/issues

<img width="1235" alt="Screen Shot 2022-10-17 at 14 58 49" src="https://user-images.githubusercontent.com/30540958/196254734-734bbecd-6393-462e-ab8d-c5642a9e64a8.png">

**Comment by Chimatara** [comment]
HI @pazbc  what do you think should be replaced with "enable a small website via GitHub"

**Comment by AndreaSanchezTapia** [comment]
Hi @Chimatara it's only deleting that item, with no replacement.

**Comment by Chimatara** [comment]
Alright, I'll make the changes you proposed and pull a request.

**Comment by AndreaSanchezTapia** [comment]
👋 Thanks, @Chimatara! can you remove L.192 "Enable a small website via GitHub"? and edit L.223 and L.336 L.519 to OLS-6?

**Comment by Chimatara** [comment]
I'll get on it ASAP.
