### ISSUE TITLE
No Link Inserted to contact the support Team

### ISSUE THREAD

**Issue by Chimatara** [open-life-science/open-life-science.github.io#474]
Hi!
I'm an outreachy Applicant.
In the OLS application guidelines, I noticed in the paragraph where applicants were asked to contact the support team if any help is needed. I think a link should be inserted in the "OLS team" for easy accessibility so applicants do not have to go looking for how to reach the team.

Thank you
![Untitled design](https://user-images.githubusercontent.com/65595525/196257022-e18bfa19-a2a9-4e70-82ac-4e05d2ad62bd.png)

**Comment by Chimatara** [comment]
I can fix the issue

**Comment by bebatut** [comment]
I assigned this issue to you @Chimatara

**Comment by Chimatara** [comment]
Thank you.

**Comment by Chimatara** [comment]
Hello @bebatut I have fixed the issue, here is a link to the PR Chimatara:My-Changes

**Comment by Chimatara** [comment]
Hello @bebatut 
I have fixed the issues and made a pull request, here is a link to review the changes made.
https://github.com/open-life-science/application-forms/pull/6
