### ISSUE TITLE
No favicon 

### ISSUE THREAD

**Issue by thechimdi** [open-life-science/open-life-science.github.io#475]
It would be good to have a favicon consistent with the OLS logo instead of just using text

**Comment by AndreaSanchezTapia** [comment]
Hi, @thechimdi, thanks for commenting. Please check if this is the same topic mentioned in issue #450. As @bebatut mentioned there, this can be worked on by the interns when rebranding.

**Comment by AndreaSanchezTapia** [comment]
I will close this issue and you can comment there (#450)
