### ISSUE TITLE
'Our Stories' Timestamp and Authors blending in

### ISSUE THREAD

**Issue by 1Joda** [open-life-science/open-life-science.github.io#480]
Hi!
I noticed that in 'Our Stories' the authors and timestamp blend in with the excerpt of the story.
When the fix for removing the lines underneath links is implemented, it will blend in more

I think we should make the font size smaller (especially the timestamp's) and separate the two (The timestamp to be aligned on the left, and the authors aligned on the right - on the same line)
![Screenshot (45)](https://user-images.githubusercontent.com/102422875/196755667-135ca4e8-3bbb-4af9-a081-2e8afa1977a9.png)

**Comment by 1Joda** [comment]
I can work on this @bebatut

**Comment by yochannah** [comment]
closing as out of date. Thanks 1Joda! :)
