### ISSUE TITLE
Proper Alignment on Images and Texts in the "STORIES" Page

### ISSUE THREAD

**Issue by Chimatara** [open-life-science/open-life-science.github.io#483]
Hello.
I noticed while interacting with the website that the images and texts on the "stories" page needs to be proper aligned so not to distract the attention of readers. I also think that the introduction to some stories should be reduces so their is uniformity with those that have short introduction.

Hi @bebatut what do you think?

**Comment by bebatut** [comment]
This issue is similar to the one here #433
Please comment there

**Comment by Chimatara** [comment]
Thank you!
