### ISSUE TITLE
Images on the Stories page do not allign

### ISSUE THREAD

**Issue by tolubishops0** [open-life-science/open-life-science.github.io#485]
The images in the stories page are not aligned as there are some  images with wider widths and heights from others. And also I think the texts underneath said images are not justified and their widths do not match that of the images above them.
 
This makes the page and markup generally not aligned

**Comment by bebatut** [comment]
This issue has already been raised here  #433

**Comment by tolubishops0** [comment]
Sounds good! 
thanks
