### ISSUE TITLE
When multiple authors the 'by' section of the project gets messy

### ISSUE THREAD

**Issue by vasconsaurus** [open-life-science/open-life-science.github.io#488]
### Description
1. Inside projects in the [projects and participants page](https://openlifesci.org/ols-1/projects-participants/#projects), when we have multiple authors and are viewing on mobile, the avatars stick to the links underlines. This however might be solved by [PR#430](https://github.com/open-life-science/open-life-science.github.io/pull/430).

2. This might be more subjective, but I think it could also be a bit better to read if with aligned the avatar and text by their center. But this should also be done after #430 is merged.

### Image of the behavior
![Screen Shot 2022-10-22 at 14 20 26](https://user-images.githubusercontent.com/87862340/197357590-6623f8fa-38e3-4a6e-a7ff-d32b044969c6.png)

**Comment by vasconsaurus** [comment]
What do you think @bebatut? Could I work on this after #430 is merged?

**Comment by bebatut** [comment]
I think you could already work on that if you want, I think it is independent of the link in #430. It is more about alignment of the text and avatar. So I would say, go for it if you want to work on it

**Comment by vasconsaurus** [comment]
thanks @bebatut, I'll work on it 🙂
