### ISSUE TITLE
Create a mentor handbook

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#49]
I have a copy of the one for MOL7 that we could use as example

**Comment by bebatut** [comment]
To add (from cohort call):

- Starting your Mentoring Relationship Checklist
  - Matching
  - Before the meeting
  - The first meeting
  - Share your story
  - Discuss Communication Styles
  - Set Goals
  - Establish the Flow
- The commitment - Before embarking on a mentoring relationship, be sure that you have the time and energy to dedicate to your mentee.
  - Provide mentors with opportunities to reflect on whether or not they have the capacity to do this before and during selection, before the program begins.

**Comment by yochannah** [comment]
This exists :)
