### ISSUE TITLE
Link Overflows From Bio-card.

### ISSUE THREAD

**Issue by NPDebs** [open-life-science/open-life-science.github.io#495]
**Current behaviour:**
On the ["peoples"](https://openlifesci.org/people) page, a participant's bio contains a link that overflows from her card.

![Screenshot (331)](https://user-images.githubusercontent.com/105166953/197896480-72043e45-16bc-4259-946b-9a6a619e31ea.png)

**Expected behaviour:**
See line 5262 to 5270 of the [people.yaml](https://github.com/open-life-science/open-life-science.github.io/blob/main/_data/people.yaml) file. The **affiliation** should be a university, but has a url instead.

**Comment by NPDebs** [comment]
Hi @AndreaSanchezTapia, @bebatut & @yochannah. 👋 

This caught my eye when working earlier. Please have a look when you get the chance. Thanks! 🙌❤️

**Comment by bebatut** [comment]
Nice catch! Thanks for reporting this issue

**Comment by NPDebs** [comment]
> Nice catch! Thanks for reporting this issue

Thanks, @bebatut. 😃
I'll go announce this on the Slack channel. See if any newcomers want to pick it up! 😄🏃

**Comment by Jolah1** [comment]
Hi @bebatut can i work on this issue?

**Comment by bebatut** [comment]
Sure. I assign it to you

**Comment by Jolah1** [comment]
on it........Thank you.

**Comment by Everythinglayemi** [comment]
> > Nice catch! Thanks for reporting this issue
> 
> Thanks, @bebatut. 😃 I'll go announce this on the Slack channel. See if any newcomers want to pick it up! 😄🏃

**Comment by Everythinglayemi** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/103745001/198074459-bd995b88-9cfd-4265-862d-cc56cd6238eb.png)

On the [peoples](https://openlifesci.org/people) page, participants card information are not properly aligned and the white spaces are inconsistent 

@bebatut @yochannah

**Comment by Everythinglayemi** [comment]
> ![Screenshot (3)](https://user-images.githubusercontent.com/103745001/198074459-bd995b88-9cfd-4265-862d-cc56cd6238eb.png)
> 
> On the [peoples](https://openlifesci.org/people) page, participants card information are not properly aligned and the white spaces are inconsistent
> 
> @bebatut @yochannah I would like to work on this

**Comment by bebatut** [comment]
Fixed with #498
