### ISSUE TITLE
Create mentor/expert registration form

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#50]
following on from #24, potential mentors should be able to express and update their preferences - probably via google form? I'll check if this can also b emanaged in easychair first, given #33

**Comment by yochannah** [comment]
https://docs.google.com/forms/d/1o0GSbDW6xx6gKay-ba3e4Z4FHdmxcufbcgYyWJXnrLo/edit

**Comment by yochannah** [comment]
I feel that generally fewer questions (and less work for mentors) is kinder to them - but if we feel it's really important info then we should go ahead.

**Comment by bebatut** [comment]
We could add just the first question and does not make it mandatory (mentionning that it is only to help us attributing the reviens)

**Comment by yochannah** [comment]
works for me!

**Comment by bebatut** [comment]
We are good with the form
