### ISSUE TITLE
Stories page

### ISSUE THREAD

**Issue by tnwoodard** [open-life-science/open-life-science.github.io#507]
On the stories page, two cool features would be: 

1. a search bar to search for stories
2. hashtag the stories by its category like #announcements or #advice

**Comment by adetyaz** [comment]
@tnwoodard hello please can I work on this or join you if you are already, and can it be assigned/co-assigned to me @bebatut.

**Comment by tnwoodard** [comment]
Hi @adetyaz and @bebatut. It hasn't been assigned to me yet, but I'm open to working on it with you.

**Comment by adetyaz** [comment]
@tnwoodard hello, have you started on this, so I know what part to pick and work on. I'm quite knew to using jekyll, I'd like to message on slack to know how to move forward

**Comment by tnwoodard** [comment]
@bebatut Is it ok to start working on this enhancement with @adetyaz?

**Comment by bebatut** [comment]
Regarding your ideas:
1. What do you have in mind for the search bar? How would you do that? Where?
2. Regarding the tags, @oluwatobiBolu is already working on it in this PR #482

**Comment by tnwoodard** [comment]
1 and 2. I'm thinking of a basic search bar using HTML, CSS and Javascript at the top of the page. With each keystroke, an event listener in Javascript will get the search input and display the article that is the closest match. After @oluwatobiBolu finishes, I can try to add a feature in the search bar to search by category/tag as well.

Thank you for your consideration!

**Comment by tnwoodard** [comment]
@bebatut: I have decided to work on the search bar. I will provide a search bar before the 3 day mark.

@adetyaz: If it is regarding the search bar, I prefer we communicate in this thread. That way we can avoid confusion, and @bebatut can have a record of our communications.  Thanks.
