### ISSUE TITLE
overflow in the mentees page for OLS/6 even for small screen

### ISSUE THREAD

**Issue by Munnachienyi** [open-life-science/open-life-science.github.io#511]
I was scrolling through the mentee's page for cohort 6 and found out there was a link overflowing where the location of the mentee is placed. 

here is a picture:
![Screenshot_20221031_085223](https://user-images.githubusercontent.com/105428107/198959546-c6dd5605-414c-4289-8097-9565b23bde7f.png)

**Comment by AndreaSanchezTapia** [comment]
Thank you! this was pointed out in issue #506 and @adetyaz worked on it. I will close this due to repetition.
