### ISSUE TITLE
Add mastodon profiles to user card display

### ISSUE THREAD

**Issue by nickynicolson** [open-life-science/open-life-science.github.io#521]
eg those shown under:  https://openlifesci.org/ols-6/projects-participants/#participants

- [x] Add mastodon profile link to `_data/people.yaml`
- [x] Modify `_includes/people.html` to display mastodon profile link with appropriate fa icon (`<i class="fab fa-mastodon"></i>`)
- [x] Modify README instructions on manual addition of people to include mastodon profile details, if available
- [x] Add `people-card-meta-mastodon` as per `people-card-meta-twitter` to CSS in `css/custom.scss`

**Comment by NPDebs** [comment]
Fixed with #523. Thank you, @nickynicolson! 🎉
