### ISSUE TITLE
Announcement of the program for MozFest

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#53]
We need to draft an announcement for the program that will eventually be posted to Mozilla Pulse & this language will appear in MOL promotions

It should include:
- Title (80 characters)
- URL
- Description: Simple, brief language works best. No jargon. (600 characters)

**Comment by bebatut** [comment]
Title: Open Life Science
URL: https://openlifesci.org/
Description: The Open Life Science program helps early stage researchers and young leaders in becoming Open Science ambassadors. Participants of this 15-week mentoring & training program will learn essential knowledge required to create, lead, and sustain an Open Science project, connect with members across different communities, backgrounds, and identities by sharing their experiences and expertise, be empowered to become effective Open Science ambassadors in their communities.
We are recruiting for our first cohort to start in January 2020, but also mentors and experts.

@malvikasharan, @yochannah what do you think?
We could add that on the top of the main page and move the POP to the syllabus.

**Comment by yochannah** [comment]
Great, but I'd remove the word young. It's often the same as ECR, but not always, and it might exclude people who don't feel they're young enough. The last sentence is also very long - how about this? 

>The Open Life Science program helps early stage researchers and potential leaders to become Open Science ambassadors. Participants of this 15-week mentoring & training program learn essential knowledge required to create, lead, and sustain an Open Science project, connect with members across different communities, backgrounds, and identities by sharing their experiences and expertise. Participants are empowered to become effective Open Science ambassadors in their communities.
We are recruiting for our first cohort to start in January 2020, but also mentors and open science experts.

Other than than, it's brilliant. ⭐️

**Comment by bebatut** [comment]
Thanks for the review. I posted it on Slack

**Comment by bebatut** [comment]
We need now to post it on [Mozilla Pulse](https://www.mozillapulse.org/add?tags=olx) ahead of the pitch!

**Comment by bebatut** [comment]
Thanks to @yochannah, it is now on Pulse
