### ISSUE TITLE
Add linkedin in the footer

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#541]

**Comment by kodervine** [comment]
Hi Bebatut,

I'd been working on this. However, the linkedin reference just shows blank on reload.
![image](https://user-images.githubusercontent.com/94802946/213774580-b43ab8c3-4477-435d-a76a-41aff739547a.png)

This is the edit I implemented on the _config.yml file
![image](https://user-images.githubusercontent.com/94802946/213774729-2aada0b7-edcf-440d-b7f0-25edae6ce4d3.png)

And this is the default rendering on the default-footer.html file
![image](https://user-images.githubusercontent.com/94802946/213774890-c699c0cf-0694-4880-a052-f52e12076336.png)

**Comment by yochannah** [comment]
clsoing as out of date
