### ISSUE TITLE
Mismatch in the number of OLS-6 projects

### ISSUE THREAD

**Issue by peranti** [open-life-science/open-life-science.github.io#558]
The about page and [projects](https://openlifesci.org/about#projects) sections show that there were 0 projects in OLS-6. However, it should have been [27 projects](https://openlifesci.org/ols-6/projects-participants/).

I couldn't find the source to fix this.

**Comment by bebatut** [comment]
@NPDebs could you have a look and fix this issue? Thanks a lot
Side node: could you also add OLS-7 there?

**Comment by NPDebs** [comment]
Sure, @bebatut. On it.

**Comment by bebatut** [comment]
Thanks!

**Comment by bebatut** [comment]
Fixed by #583
