### ISSUE TITLE
Add a sitemap

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#606]
[Sitemaps](https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview) is basically a directory listing of all the pages on the site

**Comment by richarddushime** [comment]
is this issue still open to be worked on ?

**Comment by bebatut** [comment]
This issue is still open.
The idea would be to use the Jekyll Sitemap Generator Plugin: https://github.com/jekyll/jekyll-sitemap

**Comment by richarddushime** [comment]
let me check it out 
if i get stack i will  tell you 
Thank you
