### ISSUE TITLE
Adding a Favicon to OLS website

### ISSUE THREAD

**Issue by richarddushime** [open-life-science/open-life-science.github.io#628]
**Description:**
A favicon is a crucial element for a website's visual branding and recognition. It appears in the browser tab or bookmark bar and helps users easily identify the site.
**Request:**
I kindly request adding a favicon to the OLS website for all pages.
![favicon](https://github.com/open-life-science/open-life-science.github.io/assets/45734838/fb0fcbd1-a849-476f-b6be-76b212ecd46f)

**Favicon Image:**
i will use this OLS Logo 
<img src="https://github.com/open-life-science/open-life-science.github.io/assets/45734838/5aafa202-40c9-4f1c-b77a-aa04e621cacf" alt="logo without full name" width="300" height="auto" />  | or this | <img src="https://github.com/open-life-science/open-life-science.github.io/assets/45734838/d2f61382-cba3-446e-8969-233cdb46c538" alt="open seeds logo full" width="300" height="auto" />

**Implementation:**
The favicon can be added by modifying the website's HTML layout file (e.g., `_layouts/base.html`) to include the favicon link tag in the head section.

**Consistency:**
Having a favicon across all pages will maintain visual consistency.

**Benefits:**
- Improved visual branding and recognition
- Enhances professionalism and user experience

**Comment by richarddushime** [comment]
Hi @bebatut @NPDebs 
Kindly take  a Look in the above issue i created and let me know so that i can proceed with it if possible 
Thanks

**Comment by pherterich** [comment]
There's also #450 which should potentially also be closed if the PR is merged.

**Comment by richarddushime** [comment]
Hi @pherterich 
i have just created 2 PR with different view  with 2 different logo 
this #631  and this #629 
Thank you

**Comment by yochannah** [comment]
completed and merged
