### ISSUE TITLE
Make QR (links) page responsive.

### ISSUE THREAD

**Issue by NPDebs** [open-life-science/open-life-science.github.io#638]
**OBSERVED BEHAVIOUR**

The newly created [QR page](https://openlifesci.org/links)  containing important links for OLS looks good on desktop. However, it is not very responsive on mobile. Some texts are spilling out of their containers, as seen in the image below.

![IMG_20230726_091745](https://github.com/open-life-science/open-life-science.github.io/assets/105166953/888674cf-0d1e-4538-bbce-ed66fbab62cb)

**EXPECTED BEHAVIOUR:**
Make page responsive, with content occupying appropriate width and height.

**ADDITIONAL INFORMATION:**
- The layout for this page is found [here](https://github.com/open-life-science/open-life-science.github.io/blob/main/_layouts/links.html).
- The styling for this page is located [here](https://github.com/open-life-science/open-life-science.github.io/blob/8dcdbe359c4fe6eb89b702b544074a3e6f8eb087/css/custom.scss#L431)  in this [stylesheet](https://github.com/open-life-science/open-life-science.github.io/blob/main/css/custom.scss).

Thank you!

**Comment by yochannah** [comment]
This is quite out of date - @NPDebs can you review and update the status when you have time?

**Comment by NPDebs** [comment]
Fixed with PR #860.
