### ISSUE TITLE
Rebranding: Handling "people" information

### ISSUE THREAD

**Issue by NPDebs** [open-life-science/open-life-science.github.io#639]
Regarding the process of splitting the current website, a question has come up about what information should be shared by both websites. Earlier, we had decided that the entire [_data](https://github.com/open-life-science/open-life-science.github.io/tree/main/_data) folder (with exception to the `_cohorts` subfolder) should be present in the [ols-theme](https://github.com/open-life-science/ols-jekyll-theme) repository. This decision was made to ensure that we can filter the data and display people who are in OLS in the _we-are-ols.org_ website and display the members of different cohorts in the [openseeds.we-are-ols.org](http://openseeds.we-are-ols.org) website.

However, without the [_cohorts](https://github.com/open-life-science/open-life-science.github.io/tree/main/_data) subfolder in both repositories, we might encounter challenges when trying to filter the data and display information. For instance, the people in we-are-ols.org will have no information about their participation or roles in cohorts.

Also, the new [video library](https://openlifesci.org/library) draws on information from many files in the _data folder, including the _cohorts subfolder. There may be issues with the page if the _data folder located in the theme is missing a component. 

**Questions**
- How do we manage to the people data efficiently to avoid broken parts of both websites?

**Comment by bebatut** [comment]
My thoughts:
- We put `people` in theme GitHub repo and so will be available in every website using it
- We put `cohorts` and `library` in Open Seeds
- We do not display the roles in the OLS organization website, only in the Open Seeds one

**Comment by NPDebs** [comment]
Thanks a lot, @bebatut. With the new structure (where the both websites reside in the same repo), we do not need to store _people_ info separately. Do we still need to leave this issue open?

 What say you? 😀

**Comment by bebatut** [comment]
We can close it. Thanks
