### ISSUE TITLE
Remove _cohorts subfolder from _data folder in theme repo

### ISSUE THREAD

**Issue by NPDebs** [open-life-science/open-life-science.github.io#642]
The `_data` folder should be kept in the theme, but the `_cohorts` subfolder removed, as it is not needed in the _we-are-ols.org_ website.

By doing this:
- The `people` info will be stored in theme repo where it will be available in every website using it.
- Cohort information will not be stored in the theme, but in the openseeds repo.

**Comment by yochannah** [comment]
No longer applies under the new single-website plan
