### ISSUE TITLE
We-are-ols Repo: About page

### ISSUE THREAD

**Issue by NPDebs** [open-life-science/open-life-science.github.io#646]
- [x] _About_ page
   - [x] People page
   - [x] Team and community
   - [x] Funding and supporters
   - [x] Partners

**Comment by yochannah** [comment]
The content currently in this location was for openseeds, so we need new we-are-ols content.

**Comment by NPDebs** [comment]
_closed with website restructure PR #653._

**Comment by NPDebs** [comment]
_closed with website restructure PR #653._
