### ISSUE TITLE
Update email, URL, etc in the config file

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#659]
- [x] Update email
- [ ] Update url 
   
   for now [we-are-ols.org](http://we-are-ols.org/) forwards to [openlifesci.org](http://openlifesci.org/), so we’ll need to time the changes carefully if we want to have we-are-ols be the “primary” url

**Comment by yochannah** [comment]
I DIDDDDDDD IT #844 #842
