### ISSUE TITLE
Link Text Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [open-life-science/open-life-science.github.io#664]
The current design of the link texts is nice but it can be improved by making the design differentiation between bold text (that requires user focus) and link text. The current design of bold text and link text is almost same, causing confusion for the user. We can differentiate link texts by adding more design details in it. This can be done by selecting different color for link text which will add more value in the overall design of the website.

## Sample Work

**Current Design**

![input (1)](https://github.com/open-life-science/open-life-science.github.io/assets/115794049/6a30e43b-411b-40ff-a1b5-89627d6467ea)

**Expected Updated Design**

![input (2)](https://github.com/open-life-science/open-life-science.github.io/assets/115794049/ed874c70-9c36-43d1-b437-69dd9149fa8a)

**Comment by yochannah** [comment]
closing this issue as part of an old issue cleanup. Thanks for the contribution!
