### ISSUE TITLE
Open Seeds pages

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#667]
Here some ideas for the Open Seeds pages

- Index
  - Add counts of cohorts and some stats
  - Add the library
- About
  - Program structure overview
  - Impact
  

Inspiration:
- Poster: http://bebatut.fr/posters/23/06_elixir_ahm_ols/poster.png
- BOSC slides: https://docs.google.com/presentation/d/1GJFhdlBLgC_OIJOXyXv5rc4l5BgCEjQJfXTsAm7OMQo/edit?usp=sharing

**Comment by NPDebs** [comment]
I think we fixed this with #688. Can we close this, @bebatut? 🙏🏻
