### ISSUE TITLE
To fix 

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#709]
- hover effect on cards
- different heights for cards

**Comment by yochannah** [comment]
hover effect preview. presents as a green dot when not hoevered, or a line when hovered. 

![hover effect, showing inappropriate line](https://github.com/open-life-science/open-life-science.github.io/assets/9271438/f31c0e43-fcef-4cf6-9201-445ecc3e0b8a)

**Comment by NPDebs** [comment]
Fixed with #741 & #753. Thanks, B.B & Y.Y! ❤️
