### ISSUE TITLE
Bug in BioSchema implementation

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#727]
JSON contains linebreaks in some places which is not permitted, e.g.

![image](https://github.com/open-life-science/open-life-science.github.io/assets/1842467/569540c6-7961-413d-9cd4-1d95a2e3f310)

**Comment by bebatut** [comment]
To be valid JSON-LD IDs the spaces need to be escaped, so ""Open Life Science-OLS Introduction-1" becomes "Open%20Life%20Science-OLS%20Introduction-1" for example.
there is another slight issue with that too, because `@ids` are URIs, so the above would actually be the short form of https://openlifesci.org/openseeds/Open%20Life%20Science-OLS%20Introduction-1 which does not actually resolve to any page.
typically when using an `@id` that does not point to a URL, you can use # at the start, so altogether it would look something like `"@id" : "#Open%20Life%20Science-OLS%20Introduction-1`

**Comment by yochannah** [comment]
idk if this is related or not to the failures of structured metadata warnings we've been getting from google's search dashboard - flagging for @NPDebs's attention.

**Comment by NPDebs** [comment]
Thanks for flagging!

It most likely is related. This is on my radar now, so we'll see. 👀
