### ISSUE TITLE
Add governance committee to OLS website. 

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#742]
The page should be replica of the team page: https://openlifesci.org/community.html

Profile for all members should be in our database already - but some people may need their bio updated - I"ll share the link to the google doc in slack with @NPDebs

**Comment by yochannah** [comment]
fresh please, like a lovely fruit salad

**Comment by NPDebs** [comment]
I was thinking fruit parfait, but okay. 😄

**Comment by NPDebs** [comment]
Closed with #743. Thank you!
