### ISSUE TITLE
Create online forum

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/open-life-science.github.io#75]
- [ ] Connect Gitter to the GitHub
- [ ] Slack in future?

**Comment by malvikasharan** [comment]
Gitter - not connected yet: [![Gitter](https://badges.gitter.im/OpenLifeSci/community.svg)](https://gitter.im/OpenLifeSci/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

Need review and permission.

**Comment by bebatut** [comment]
I think this issue is outdated. Feel free to reopen if not
