### ISSUE TITLE
Structured metadata failures

### ISSUE THREAD

**Issue by NPDebs** [open-life-science/open-life-science.github.io#756]
Prompted by Google's _Search Console_, we observed some structured data issues. These were detected specifically in the `hasCourseInstance` property of our [schedule schema](https://github.com/open-life-science/open-life-science.github.io/blob/bf73c2f4237adea1bf10457baf9aa97e179e7e16/_includes/schedule.md?plain=1#L1).

**See screenshot below:**
![schema_issue](https://github.com/open-life-science/open-life-science.github.io/assets/105166953/042d1ffe-a543-44b5-abae-399dbdff1b8e)

**Two categories of issues require attention:**
1. _Critical issues_: which prevent the page from appearing in search results.
a. Either `courseWorkload` or `courseSchedule` should be specified (in `hasCourseInstance`).
b. Missing field `offers`.

2. _Non-critical issues_: which are suggestions for improvement, but don't prevent the page from appearing in search results.
a. Invalid enum value in field `courseMode` (in `hasCourseInstance`).

**Comment by bebatut** [comment]
Thanks for investigating.
How do you think we can fix that?

**Comment by NPDebs** [comment]
Yeah, I was going to follow up the issue with a comment on a possible fix.

With the info provided by [schema.org](https://schema.org/hasCourseInstance), I had this approach in mind...

> b. Missing field `offers`.
The `"@type": "Offer"` accomodates pricing information for courses. Since, ours is free, I suggest we indicate that like this:

```
  "hasCourseInstance": [
      "offers": {
        "@type": "Offer",
        "price": "0",
        "priceCurrency": "GBP"
      }
]
```

**Comment by NPDebs** [comment]
Exactly!

And for the `courseMode`...I'm not sure why it's been flagged sine we have something in that field.
```
    "courseMode": ["online", "synchronous"]
```
