### ISSUE TITLE
Expand events to support event page creation

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#758]
It might be good to have 2 types of events listed on the website
- events we participate in, where we give talks, etc
- events we organize for which we could have a dedicated page

# Possible implementation 

All events could be stored as individual Markdown with some YAML metadata in a `events` folder, a bit like the blog post.
If there is more than just YAML a page is automatically created
All events would be used to automatically fill an event page showing events in a table sorted by date

Does that make sense?
Any other ideas?
@NPDebs, @yochannah, @malvikasharan, or anyone else?

**Comment by yochannah** [comment]
This sounds like a great approach to me! 

I would like to plan training events anyone can sign up to - like Ally Skills - would these fit in there

**Comment by bebatut** [comment]
> I would like to plan training events anyone can sign up to - like Ally Skills - would these fit in there?

I do not understand your question

**Comment by yochannah** [comment]
Ahh, sorry. I mean: would this page be only for things like invited events, or could it also be a place to centralise links / sign-up to potential events in the future?

**Comment by bebatut** [comment]
I think I still do not follow you 😅
Do you have examples in mind?

**Comment by yochannah** [comment]
haha oops 😂

**Comment by yochannah** [comment]
Examples of events I am thinking of: 
1. Invited talk at a conference. Associated data: conference name, conference link, date, name of speaker, slides link, recording link. 
2. Ally skills training (or any other possibly for-pay training) : Associated data: Trainers names, registration link, date, duration (e.g. 3 hours), fee structure (if any), materials link(s), recording link (if relevant). 

As you see the two use cases are similar but slightly different.

**Comment by yochannah** [comment]
fabulous!!

**Comment by bebatut** [comment]
Fixed with #768
