### ISSUE TITLE
Migrate policies, procedures, and docs here? 

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#760]
This repo: https://github.com/open-life-science/policies-procedures-and-docs/

would make a lot of sense if it was on the website here, now. At the time I started it, the website was _only_ open seeds stuff, so a separate repo was logical. Now, though, the boundaries between the two repos are not so clear, so maybe we make them one larger repo? 

I'd appreciate a thumbs-up from @bebatut if you agree this is logical? If not, happy to close this issue.

**Comment by bebatut** [comment]
Yes!!
(I thought we already agreed on doing it and that @NPDebs was supposed to do it)

**Comment by yochannah** [comment]
heheh, I thought we had too but was only 87% sure 😁

**Comment by yochannah** [comment]
@NPDebs a gift, of work, for you. 😂

**Comment by NPDebs** [comment]
You speak my language, Yochannah. 😍

Added to to-do list. ✔️

**Comment by bebatut** [comment]
Fixed with #764
