### ISSUE TITLE
Implement Nebula site

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#765]
At a prompt from @bebatut 

- how do we show facilitator roles, and differentiate between cohort participation in different types of cohorts? 
- How do we show people just in one cohort type or the other?

**Comment by yochannah** [comment]
tagging @NPDebs for thinking about the technical parts of this, and @iramosp in case she has comments

**Comment by NPDebs** [comment]
Thanks for tagging! She's been thinking a lot about how best to implement not just facilitator roles, but the new subsite infrastructure.

## Displaying people info (`/people` page)...
I think it's proper to maintain the current structure where we have everyone in [one place](https://openlifesci.org/), regardless of their program.

For that, we can add the new Nebula-1 participants' info into the [people.yaml](https://github.com/open-life-science/open-life-science.github.io/blob/main/_data/people.yaml) file.

## Isolating nebula-specific info
Within the `data` directory, we create a new sub-folder for _nebula_.

```
_data/nebula/neb-*/
      metadata.yaml
      projects.yaml
      schedule.yaml
```

### Facilitator roles

Right now, this [line in the people.html file](https://github.com/open-life-science/open-life-science.github.io/blob/098814c556406fb8536aa1f683be0e4b3c37bff9/_layouts/people.html#L41) iterates over the _openseeds_ folder. With nebula also available in the _data folder, we can add it to the loop. Something like this:

```
{% assign openseeds_cohorts = site.data.openseeds %}
{% assign nebula_cohorts = site.data.nebula %}
{% assign all_cohorts = openseeds_cohorts | concat: nebula_cohorts %}

{% for entry in site.data.people %}
  ...
  <!-- Extract roles for people in all cohorts -->
  {% for cohort in all_cohorts %}
    {% assign projects = cohort.projects %}
    {% assign metadata = cohort.metadata %}
    {% assign schedule = cohort.schedule %}
      ...
  {% endfor %}
{% endfor %}

```
So far, this is the line I am thinking in. Please, let me know if something isn't clear.

**Question** - do we want to prioritise adding these people to the website?

**Comment by bebatut** [comment]
Sounds like a good plan
We could think later to have in each subsite people page displaying only people of the corresponding program

**Comment by NPDebs** [comment]
> Sounds like a good plan
> We could think later to have in each subsite people page displaying only people of the corresponding program

Yeah! 💯 _.../openseeds/people_...
That would be a nice feature.

**Comment by NPDebs** [comment]
Thanks, @bebatut. 🙏

> Question - do we want to prioritise adding these people to the website?

By this I mean, do you think it makes sense to relegate current tasks (e.g creating the events page), in order to implement this new subsite infrastructure? 

Personally, I think this is more important. Can I get your thoughts, please?

**Comment by bebatut** [comment]
Probably need @yochannah's input there

**Comment by yochannah** [comment]
yes, I think that's a good choice!

**Comment by NPDebs** [comment]
> yes, I think that's a good choice! 

Thanks for the feedback! ✨

**Comment by yochannah** [comment]
completed with #867
