### ISSUE TITLE
Update staff page

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#774]
Following on from #771 and #772: 

- I'm not sure on the right terminology here, but we should add a "previous team members" section, and move Emmy into it 😭 
- let's update Catalyst: I'm OLS-PI-ing it now, since Emmy has left :( 
- Any other changes to make?

**Comment by bebatut** [comment]
Should we use `alumni`?

**Comment by yochannah** [comment]
yes, let's go for alumni!

**Comment by NPDebs** [comment]
Thanks, @bebatut and @yochannah! Updated in PR #776.

**Comment by NPDebs** [comment]
Echoing Yo's earlier question. 🙏 

> Any other changes to make?

**Comment by NPDebs** [comment]
If there are no additional comments or suggestions, I would love to close this issue, please.

**Comment by bebatut** [comment]
> let's update Catalyst: I'm OLS-PI-ing it now, since Emmy has left :(

Have you updated Catalyst to add Yo?

**Comment by NPDebs** [comment]
Thanks for pointing it out! I just updated it. 🙏 

Question - shall we:
- temporarily _unmerged_ #776, add the change and merge again,
- or create a new PR for adding Yo.

**Comment by bebatut** [comment]
A new PR is perfect :)

**Comment by NPDebs** [comment]
Fresh PR available at #779. Thanks!
