### ISSUE TITLE
Add The Catalyst Project to the OLS website

### ISSUE THREAD

**Issue by NPDebs** [open-life-science/open-life-science.github.io#787]
**Current behaviour:**
The project is being exposed only in the [open-incubator](https://openlifesci.org/open-incubator.html#catalyst) page, and has little visibility on the website.

**Expected behaviour:**
Create a sub-site for The Catalyst, mirroring the existing [openseeds](https://openlifesci.org/openseeds/) infrastructure, and populate with necessary data related to the program.

**Comment by yochannah** [comment]
@Tajuddeen1 can you please post the timeline here?

**Comment by NPDebs** [comment]
Going by the planning sheet, it should be August 26th to December 9th, 2024.
