### ISSUE TITLE
Add Rowland's RSE leadership training to site

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#791]
@rowlandm will deliver a training course later this year. 

@NPDebs - can you please help him get the course description online? 

Partial to-do list: 

- [ ] dates in ols public calendar
- [x] informational page up and linking to ticket page
- [ ] marketing materials
- [x] ticket platform setup
- [ ] store credentials in ols keybase or invite additional users for ticket platform

**Comment by NPDebs** [comment]
_I'm all over it!_

**Comment by NPDebs** [comment]
@yochannah I will be PR-ing just the course description for now. Any plans to add the ticket pricing options (and duration?) before merging?

**Comment by yochannah** [comment]
pricing - £499 gbp for initial skills consult and personal development plan, £1999 for 5-7 modules based on the initial consultation.

**Comment by yochannah** [comment]
@rowlwandm will correct me when he's awake, I'm sure 😁

**Comment by NPDebs** [comment]
Rowland doesn't sleep, silly!

**Comment by NPDebs** [comment]
@yochannah One thing - would I be correct to include this line?

**"LMIC discounts are available for all offers..."**

**Comment by yochannah** [comment]
you know it's true!

**Comment by NPDebs** [comment]
_Everything I do..._

Sorry. I had to.

**Comment by rowlandm** [comment]
*pricing - £499 gbp for initial skills consult and personal development
plan, £1999 for 5-7 modules based on the initial consultation.*
Yes, I'm happy with this. I was going to do the registration just for the
499 GBP. After the skills consult plus personal development plan, then we
could issue them with an invoice to do the "workshop" separately.

Do you think that would work?

**Comment by NPDebs** [comment]
@rowlandm Sounds good! So, we take out that line from the open PR, yes?

**Comment by rowlandm** [comment]
I'm happy to keep the 1999 GBP in there to show how much the total cost
would be, the registration itself would only be 499 when you pay for the
ticket...

I have added another module so it would look like:


   - 14th November - Project Management
   - *21st November* - People managing high-performance teams.
   - *28th November* - How to deal with difficult change management
   situations and build relationships.

**Comment by NPDebs** [comment]
Updated as required, @rowlandm. You can review PR #792 or checkout the [deploy preview](https://deploy-preview-792--ols-bebatut.netlify.app/consulting/organisational-leadership/#research-software-engineer-rse-leadership-training-course), and let me know if you'd like to change anything.

**Comment by yochannah** [comment]
Okay - the PR is merged! @rowlandm - reviewing the to-do list at the top of this issue, anything you need help with?

**Comment by rowlandm** [comment]
I may need help with:

Adding dates in OLS calendar 

Identify who else to connect to ticketing platform / keypads

Finance/ organisational information for ticketing platform

**Comment by yochannah** [comment]
@Camille-Gonz-VA - can you please help rowland with the Calendar?

@bethaniley - can you please help rowland with the finance aspects? 

> Identify who else to connect to ticketing platform / keypads
Please add me, @Camille-Gonz-VA, @iramosp - thanks!!

**Comment by yochannah** [comment]
I'm separating those other tasks out individually since the web part of it is complete.
