### ISSUE TITLE
Highlight the Open Science definition on the website

### ISSUE THREAD

**Issue by NPDebs** [open-life-science/open-life-science.github.io#794]
**Observed behaviour:**
Currently, the [open seeds program](https://openlifesci.org/openseeds/) is described as being targeted at people interested in applying **open principles** in their work..." This boldly highlights a term but does not provide any further information for individuals seeking more context.

Fortunately, the **Open seeds paper** summarises these concepts. As such, the goal of this issue is to call for the paper to be made more prominent on the website. 

**Expected behaviour:**
- Create a new page (`/about/open-science`).
- Explain the Open Principles.
- Highlight the Open Seeds Paper.
- Possibly, link to other useful resources (videos, articles, etc).

Thank you, @pazbc for pointing out something so critical! 🙏

**Comment by NPDebs** [comment]
@malvikasharan Here's the issue! Let me know if I have left out anything so far.

Happy to talk about it at the next team meeting!

**Comment by yochannah** [comment]
I'm going to split this into two issues. This one should be just for adding "about open science" to the page. The paper is a dependency that still has a lot of work, so we've moved its tracking to another repo

**Comment by NPDebs** [comment]
@yochannah - Is there an existing doc with content I can build this `"about open science"` section from? I'm also happy to PR a definition based on my understanding and experience.

In any case, would 100-150 words be a desirable word limit?

**Comment by bebatut** [comment]
Maybe the best would be to align with the definition we use in the Open Science introduction slides in Open Seeds

**Comment by yochannah** [comment]
Good point. @NPDebs - https://docs.google.com/presentation/d/1eKRgozsGmJvjPELyP4KMgrgHchp7o58YowC5RkgLNd4/edit#slide=id.g21d0ef90081_0_0

**Comment by malvikasharan** [comment]
+1 to @bebatut and we should use definitions as we are using in the open seeds paper draft to be consistent -- maybe more simplified with references we are primarily using. We also use UNESCO image which can be added.
