### ISSUE TITLE
Begin using GitHub project management features

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#796]
@NPDebs - based on our retro we'd like to start implementing a project management board for web tasks, so it's easy to see what is highest priority. Please have a think about a good way to start making priorities and live tasks clearer: https://github.com/features/issues 

Also happy to chat on this if you're not sure where to start! 

tagging @bebatut for awareness

**Comment by NPDebs** [comment]
Much needed upgrade! 👍🏽 

A logical next step would be to:
- create a new project (or use an existing one?),
- list current tasks,
- ensure they're in order of priority.

Does this sound about right?

**Comment by yochannah** [comment]
new board, I think! 

And hopefully most of the existing tasks are representing by issues already. If not, they should. 

Thanks!
