### ISSUE TITLE
Add Blog launch for RSE AUNZ fiscal sponsorship

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#803]
Text: https://hackmd.io/YR-f50tIR4S3Q2ru8x3vYw 

tagging @manodeep and @rowlandm

**Comment by yochannah** [comment]
Debs - low priority, but also pretty fast to do.

**Comment by rowlandm** [comment]
Hi Yo,

I was thinking also adding the main reason for the fiscal sponsorship was
the RSE Asia Australia unconference.

**Comment by NPDebs** [comment]
Yep, Rowland doesn't sleep.

**Comment by rowlandm** [comment]
Haha!

Updated the text to include rse Asia Australia. Please have a look and
adjust as appropriate :)

**Comment by NPDebs** [comment]
Thank you! ✨

**Comment by manodeep** [comment]
I made some edits and cleaned up the text a bit.

**Comment by NPDebs** [comment]
Thank you @manodeep and everyone else! Blog post is ready at PR #804. Feel free to make additional suggestions there. 🙏

**Comment by yochannah** [comment]
she's live - thanks all!!
