### ISSUE TITLE
Nebula sub site wishlist

### ISSUE THREAD

**Issue by iramosp** [open-life-science/open-life-science.github.io#841]
This issue is to sketch and discuss Nebula sub-site needs (mostly **content and structure**). We can open different issues for the actual website changes. 

I gathered some ideas we had previously discussed and complemented them with needs we learned from the pilot.

## Needs
* Website as one-pager for anyone who wants to register.
* Website as single point of information for people in the cohort (participants, speakers, facilitators coordinators).
* Automate as much as possible. Eg. populating schedule from planning sheet.
* **Structure**: Reuse much of the Open Seeds sub-site with a few changes to make navigation easier.
* **Design**: A little bit more visually distinct - just so it's easier to tell you have navigated to a different sub-site. It could be as simple as replacing OLS logo for Nebula logo and maybe changing the accent color. @jilaga is already working on some ideas.

## Sketches
I'm mostly thinking about the front end sub-site structure (ie how it looks, how users navigate), leaving the implementation and repo structure to our web dev team. 

**Structure**
```
/nebula
------- index      --> Keep what we currently have. This will be the landing page with all necessary info for registration
------- about      --> This goes under "The Program" tab
------- cohorts 
----------- nebula-2024-1     --> The current cohort
----------- previous-cohorts  --> Links to a table similar to the Open Seeds sub-site
------ resources   --> Similar to "Policies & Procedures" in Open Seeds sub-site, but show a page with links
------ about-ols   --> Same as in Open Seeds sub-site, but rename "About OLS"
------ stories     --> Same as in Open Seeds sub-site
```

**Rough visuals** (please ignore the design, I'm just trying to show how the tabs and content would be organized): https://docs.google.com/presentation/d/13AUdAFNPTiB6MKpZHi1T69Zm77SNoOf1_VjKgtaZLD0/edit#slide=id.p

**Details**

* `index` - This is what we have. Keep it to serve as the landing page with all necessary info for registration
* `about`
    * Similar to Open Seeds sub-site, a single page under "The Program" tab, with a more detailed description of Nebula, NASA TOPS, FAQ and previous cohorts.
* `cohorts` 
    * Each cohort under its own page, similar to Open Seeds sub-site structure, eg. `nebula/nebula-2024-1` Each cohort main page (`nebula-2024-1/index.md`) will include timeline, schedule, people and other basic cohort info, like in the Open Seeds sub-site. Schedule will be populated from [planning sheet](https://docs.google.com/spreadsheets/d/15cR5YsttvmbtX8q_Zt4YBangzqns3NqkisJFf3_ApZI/edit?gid=1514825681#gid=1514825681).
    * In contrast with Open Seeds sub-site, we can **keep the schedule and list of participants on the same page**, so no need for additional "schedule" or "projects-participants" pages.
    * `previous-cohorts` links to a table summarizing previous cohorts similar to Open Seeds sub-site. In Open Seeds, the table is in the `openseeds/index`, but I think it would distract from the registration info. So a better place might be in `about` page under "The Program" tab.
* `resources` 
    * Similar content to the "Policies & Procedures" tab in Open Seeds sub-site, but this is a separate page with links to relevant documentation and resources (including the video library) instead of accessing each resource via the drop down menu like it's currently implemented in the Open Seeds sub-site.
    * Behavior should be similar to https://openlifesci.org/policies-procedures-and-docs/. 
    * Documentation specific to Nebula, like the microgrant policies, will go under a `nebula/cohort-procedures-and-templates` folder like in Open Seeds sub-site so that each document is rendered in its own page. 
* `about-ols` 
    * Same as "About" tab in Open Seeds sub-site, just rename to "About OLS" to clarify that this will take you back to OLS website
 * `stories` - Same as Open Seeds sub-site

## Questions
1. Are the sketches clear? What suggestions do you have?
2. For the dev team: @NPDebs , @bebatut, Is it viable to implement this structure? Any technical considerations I might be missing?

**Comment by bebatut** [comment]
Thanks @iramosp for the detailed wishlist.

To be sure we are on the same page. When you describe the structure, you mean the navigation bar on the top. Right?

**Comment by iramosp** [comment]
Yes, I mostly mean the navigation bar. Some points might overlap with the repository structure, for example, having a `cohort-procedures-and-templates` for documentation specific to Nebula.

**Comment by iramosp** [comment]
Done! See https://github.com/open-life-science/open-life-science.github.io/pull/867
