### ISSUE TITLE
External document links open on the same tab

### ISSUE THREAD

**Issue by Tajuddeen1** [open-life-science/open-life-science.github.io#859]
When you click on a cohort presentation it opens on the same tab. I would suggest we make it open on a new tab instead.

**Comment by NPDebs** [comment]
@Tajuddeen1  - Can you please clarify if you're referring to the [video library](https://we-are-ols.org/openseeds/library.html)?

**Comment by Tajuddeen1** [comment]
For example https://we-are-ols.org/openseeds/ols-1/schedule.html#week-02 when you click on the link to the talks it opens in the same tab

**Comment by yochannah** [comment]
I'm not sure this is a feature we want to implement as there are UX and
accessibility implication:
https://www.nngroup.com/articles/new-browser-windows-and-tabs/

@bebatut wdyt?

**Comment by bebatut** [comment]
I am also not sure that we want to implement it. I heard the same arguments as @yochannah against it

**Comment by yochannah** [comment]
okay, that's enough for me in that case. Sorry @Tajuddeen1, this one's a no - please do keep suggesting features and ideas in the future though! 🙏
