### ISSUE TITLE
Add Pidgin translation of English-language blog welcoming Seun

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#861]
Same blog as #850, but in Pidgin. 

- [x] Text translated
- [x] Old post links to this one... 
- [x] This post links to old post...

**Comment by yochannah** [comment]
@NPDebs - could you cross-link the two posts as well? e.g. "This post is also available in [English](linkie here)"

**Comment by NPDebs** [comment]
@yochannah - Ready at #863.
This was a really good request. Thanks! 🙏🏽

**Comment by bebatut** [comment]
Fixed with #863
