### ISSUE TITLE
Add DRI-EDIA champions info on the OLS-9 DRA page

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/open-life-science.github.io#900]
## Summary 

- I have imported champions' data in the civil
- A mailing list has been created and individual info stored

## Open question 
- What needs to be done to add them on the website
- I am currently doing mentor-mentee group matching -- should this information be added in civi or on Github?

## Who can help?

@bebatut supervision, assigned to @NPDebs

**Comment by NPDebs** [comment]
Closed with #907. Thanks, Malvika! 🌷
