### ISSUE TITLE
"Bioschemas for mortals" consultation 

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#912]
Bioschemas for mortals

Have you used Bioschemas to markup your data, tools, training materials or other web content? Was it cumbersome, tedious, a joyous experience, or did you fail to get started?

Help our two UK co-leads, Phil Reed and Nick Juty, of this engaging 2024 BioHackathon project be ready to  reimagine, reframe and supplement the existing Bioschemas guidance available.

Internal deadline: 1 November

https://docs.google.com/forms/d/e/1FAIpQLSei0iZxzC0zQewhi33nKfDsNys33FLi11zeqDUfAoresjh1rQ/viewform

@NPDebs can you take a look and decide if you feel able to complete this? If not, no worries, we can skip it.

**Comment by NPDebs** [comment]
Closing this as discussed, for lack of capacity to handle it.
